<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MonthQuarter</name>
   <tag></tag>
   <elementGuidId>a52b13c6-462e-4f1b-bddf-32070aa53f4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filterMethod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filterMethod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5b8dd659-67d0-45da-a96d-161bc4aafb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterMethod</value>
      <webElementGuid>2e77a07c-869d-4762-a6f9-4488975fc579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterMethod</value>
      <webElementGuid>89492e70-a466-45e4-b692-aacea0a7c0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>filterMethod</value>
      <webElementGuid>dc35002c-0d57-49f0-bd4e-159e71266186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Period type</value>
      <webElementGuid>43d40ced-6341-4c9f-aae0-a795109b76e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>fba57c0e-be8e-4c44-91b5-0a60f0be3ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MonthQuarter</value>
      <webElementGuid>5fdc5e94-c8a9-46fa-beb2-9dc1d264a627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterMethod&quot;)</value>
      <webElementGuid>9c106f95-dba1-46ac-a0ed-5d3a3eb9b779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filterMethod']</value>
      <webElementGuid>49b6f90c-cf41-4e11-8e38-802130ad6285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div[2]/div/form/div/div/select</value>
      <webElementGuid>99dd9245-1657-4a2f-be2e-129e0208db39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Period type'])[1]/following::select[1]</value>
      <webElementGuid>65af7bdb-d46a-4bce-be6d-6d84480f85e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='one Portfolio'])[1]/following::select[1]</value>
      <webElementGuid>8beb2a73-270d-4806-a988-4d5841900251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Financial Year or Month'])[1]/preceding::select[1]</value>
      <webElementGuid>49602cde-1126-482b-a605-2d621d56b984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan'])[1]/preceding::select[1]</value>
      <webElementGuid>ca50555a-299d-423a-a648-c3f59822a8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>877f1a4f-d7ea-435c-b72a-f703453cdb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filterMethod' and @name = 'filterMethod' and (text() = 'MonthQuarter' or . = 'MonthQuarter')]</value>
      <webElementGuid>9f6ba00e-6177-4d35-8955-bd6e1506931b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
