<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Edit</name>
   <tag></tag>
   <elementGuidId>69c4f10c-9e1e-4575-bc13-c20334bd395b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ms-4.me-4 > a.icon-link > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='download-container']/div/div[2]/div[2]/div[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f92ceeef-3437-43bd-ac7b-8ff058c8d4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>e0961c56-f9da-49ed-bd3e-4df3fb65c56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;download-container&quot;)/div[@class=&quot;print-container&quot;]/div[@class=&quot;row mt-4 d-print-none&quot;]/div[@class=&quot;col-12 col-sm-6 col-md-5 d-flex justify-content-end align-items-center mt-4 mt-sm-0&quot;]/div[@class=&quot;ms-4 me-4&quot;]/a[@class=&quot;icon-link&quot;]/span[1]</value>
      <webElementGuid>675cdc6c-ca6c-4b9f-9162-fb1522877629</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div[2]/div[2]/div[3]/a/span</value>
      <webElementGuid>ca0bbc40-98ba-4390-9078-8fbbcfb1cd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::span[1]</value>
      <webElementGuid>4acff1a5-4a4b-40cf-8b47-d39c262e9b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/following::span[2]</value>
      <webElementGuid>8df0e01a-f898-4b89-8165-cce657658d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details Table'])[1]/preceding::span[1]</value>
      <webElementGuid>7644a316-fda1-4137-89c6-31331234ee6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly Financial Performance (000s) - July'])[1]/preceding::span[2]</value>
      <webElementGuid>2371ef37-2111-4955-a8e6-99bb38205f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>7f30fb3e-59f9-4211-a0db-f0e97831bbcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/span</value>
      <webElementGuid>053911e8-a908-4966-abd0-37eb90b0cff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>918b0835-5f38-4fea-84f3-ff5974daccac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
