<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Secondary</name>
   <tag></tag>
   <elementGuidId>49926441-5bc6-4a0b-ae9e-5b5776cfadb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ngb-nav-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ngb-nav-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>85d6310a-b0be-4bc1-a481-ed6f6e86bcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/inspections/507/111/8375/report/secondary</value>
      <webElementGuid>90e0d912-2650-4e08-a2a4-9ffb8c1b626b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ngb-nav-1</value>
      <webElementGuid>ea6b66ba-d80a-4b15-8774-8fbd35d496ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>fa02ef29-f687-4707-a55e-653182bc86cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>27c0aaac-9410-4198-b177-138d68030d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c999179e-36c5-422b-a01c-618944774068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>98900fb8-83e8-42f4-a944-5bd3b70ca8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Secondary</value>
      <webElementGuid>b083e753-92e9-45b0-8069-fc4b50cc3af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngb-nav-1&quot;)</value>
      <webElementGuid>fd08d4c5-cd20-4b87-9459-e7e1a7ef317d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ngb-nav-1']</value>
      <webElementGuid>b40fa224-0cc8-437b-8d35-3258e6c2db22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>94848982-1159-4ecb-b16c-810ee7fc9554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Secondary')]</value>
      <webElementGuid>96bac725-d237-47a3-bb08-782ba663d1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary'])[1]/following::a[1]</value>
      <webElementGuid>6db939bc-5536-426e-9ee9-11c5ef6bb61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Building Details'])[1]/following::a[2]</value>
      <webElementGuid>6872aaea-6f4b-4087-b1ea-ad0bc1b46aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forecast'])[1]/preceding::a[1]</value>
      <webElementGuid>36e15314-e265-4eb7-b2f3-7356d1bb2486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Future R&amp;M'])[1]/preceding::a[2]</value>
      <webElementGuid>bf72e1af-d326-4a0f-8dff-d2aea25e8880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Secondary']/parent::*</value>
      <webElementGuid>cfaab79f-b804-4816-85ab-5a076f178ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/inspections/507/111/8375/report/secondary')]</value>
      <webElementGuid>40e95b6d-b03d-443d-880e-a9590d92c8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>ca932450-5c4e-4700-bfe7-e8d9ca1e3f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/inspections/507/111/8375/report/secondary' and @id = 'ngb-nav-1' and (text() = 'Secondary' or . = 'Secondary')]</value>
      <webElementGuid>bbffbeef-dad6-4ded-a89e-85aa1861f263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
