<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Comic Sans MS_angular-editor-textarea</name>
   <tag></tag>
   <elementGuidId>91be890d-a9d0-4d22-8747-33d434a56d84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.angular-editor-textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='download-container']/div/div[2]/app-capex-report-secondary/div[2]/div/app-capex-report-secondary-item/div/div[2]/angular-editor/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4bf22b92-636e-45f6-927e-48fb0b430c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>angular-editor-textarea</value>
      <webElementGuid>d18686a2-a67a-40e3-a6ee-12937ae7c325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1628262c-d6f2-485f-88be-d87633bfe2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>75b4d13d-4710-4add-98bb-ec74a85f9b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d7c4ea6-5e48-4d40-9714-e7c608f74fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;download-container&quot;)/div[@class=&quot;print-container&quot;]/div[@class=&quot;card-body&quot;]/app-capex-report-secondary[1]/div[@class=&quot;list-group-flush&quot;]/div[@class=&quot;list-group-item&quot;]/app-capex-report-secondary-item[1]/div[@class=&quot;py-3&quot;]/div[2]/angular-editor[@class=&quot;ng-untouched ng-valid ng-dirty&quot;]/div[@class=&quot;angular-editor&quot;]/div[@class=&quot;angular-editor-wrapper show-placeholder&quot;]/div[@class=&quot;angular-editor-textarea&quot;]</value>
      <webElementGuid>37bdd7a8-025d-4544-a80d-ca5acb4cd14a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div[2]/app-capex-report-secondary/div[2]/div/app-capex-report-secondary-item/div/div[2]/angular-editor/div/div/div</value>
      <webElementGuid>e63b15b6-7fa0-4687-ad13-513481dd7ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//angular-editor/div/div/div</value>
      <webElementGuid>32156c5a-8ce3-4a0b-8cd7-c693daeec16f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
