<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Capital Expenditure</name>
   <tag></tag>
   <elementGuidId>33a9d833-ac12-45fb-bf47-5f34f3298c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#capexDropDown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='capexDropDown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f99d201a-27f4-4d7b-9c77-71aed083a84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>capexDropDown</value>
      <webElementGuid>ce3454c4-569b-421a-a4a3-b2280c66ed4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>567561bd-e7b9-4f53-bd4c-824ead9c698a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3897c16f-3ede-4238-99b4-01f0bbe3e806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>69b2a9fd-7b5d-42a6-a43b-fd2d2f57d082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link d-flex align-items-center show</value>
      <webElementGuid>3fe6832e-ba0a-4eb7-bc3f-89f49a7a0267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Capital Expenditure</value>
      <webElementGuid>cb54cf73-9c55-4ddf-91f1-5bb3d51a7b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;capexDropDown&quot;)</value>
      <webElementGuid>05ddcba0-a03f-4506-aae0-1d81fe2911e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='capexDropDown']</value>
      <webElementGuid>c21af06c-13a2-4139-b7cc-d599263eced4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarsExampleXxl']/ul/li[4]/div/a</value>
      <webElementGuid>fff97c2e-a240-47c2-9b14-eeba16ab2d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Capital Expenditure')]</value>
      <webElementGuid>34a73889-8266-4bb4-af4b-e12cab202e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What-if? Portfolio'])[1]/following::a[1]</value>
      <webElementGuid>2630d3f4-fdb0-4660-9222-a6cea14616cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Portfolio'])[1]/following::a[2]</value>
      <webElementGuid>43973d6c-5199-467a-bb93-b8faec9b2c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inspection List'])[1]/preceding::a[1]</value>
      <webElementGuid>bd317a60-a6e5-4c46-8095-cddc7cab4913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Inspection'])[1]/preceding::a[2]</value>
      <webElementGuid>f4ab565e-8de2-4aaa-b66c-9fec6af4b6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Capital Expenditure']/parent::*</value>
      <webElementGuid>aa8aea21-295d-4ebf-974e-b9c40e164c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/a</value>
      <webElementGuid>feaa7903-3ea8-463f-bad2-8834c2b5670a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'capexDropDown' and (text() = 'Capital Expenditure' or . = 'Capital Expenditure')]</value>
      <webElementGuid>da412d51-748c-4fa5-ba49-a6d4ed1155a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
