<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Property Type_propertyType</name>
   <tag></tag>
   <elementGuidId>2440b6ad-5940-4d5a-b0d9-6af7d1908bda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#propertyType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propertyType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a322c773-b125-455f-86a8-d290151a1cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ff883e47-63d7-4615-a3f6-a6dec4adb3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyType</value>
      <webElementGuid>1739f703-b1a6-4bdf-bcd2-365c1ac36195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Property Type</value>
      <webElementGuid>d50d6d79-4ea3-4eaa-965a-9df9d04fbb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>b09c38d3-8c11-45f0-bea3-29180dc1fcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>5bf788a8-bcd2-4b15-bf47-14b315967fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyType&quot;)</value>
      <webElementGuid>adb68a1a-ef77-4152-bb66-57ea818e851f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propertyType']</value>
      <webElementGuid>6e9f03f7-322e-4b5b-8e1a-9fae86fa96b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>b512a9bd-6ffd-441d-b773-f9d7c0949398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'propertyType' and @placeholder = 'Property Type']</value>
      <webElementGuid>225509f2-40a7-433c-b211-4f7c3062d406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
