<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Building Name_buildingName</name>
   <tag></tag>
   <elementGuidId>60047722-d76e-4de5-b5ec-25bd5ee962b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buildingName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buildingName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a212b967-c955-4ace-a55e-a2d2a37b485e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>8568d651-4e34-43e6-bce9-dc8b424b6460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildingName</value>
      <webElementGuid>022dbf49-205d-4260-abec-249245ec0d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Building Name</value>
      <webElementGuid>5f9647f9-8391-4df8-965a-df7e63304956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>71b1ee86-93a1-44dc-9a5f-13802916ce2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>4da6d0d0-df5d-4cc8-97bd-a9ba0db980d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buildingName&quot;)</value>
      <webElementGuid>d8f7e8f3-b6ea-4089-8bb7-137b576ab840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buildingName']</value>
      <webElementGuid>1832d7a7-7e25-4674-96f2-0b0a3801abdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a902ad4f-30ed-4a53-9cc7-3877c5b816af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'buildingName' and @placeholder = 'Building Name']</value>
      <webElementGuid>5145db96-1380-4862-9137-bb875e1b0384</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
