<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buildings</name>
   <tag></tag>
   <elementGuidId>8855f097-b96f-4601-be03-5baf81b8543a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buildingDropDown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='buildingDropDown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>01bdca23-27f1-425f-ba11-48fbc7ca324d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildingDropDown</value>
      <webElementGuid>078a3b02-9579-44ad-ab74-34b489454f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>7cfc6ed6-ed10-49cb-b91b-3d177582ff9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d155963c-379d-4eaf-9f72-dada46f35e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>0e84ce6e-728d-4a0a-8919-df436ea599be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link d-flex align-items-center active</value>
      <webElementGuid>43ec6e3d-d30f-4d1d-bb24-7e8931118336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buildings</value>
      <webElementGuid>1cb88e4e-8ea7-4166-aa92-ee31a0a11285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buildingDropDown&quot;)</value>
      <webElementGuid>d4e842e4-dfc8-4b26-9b43-4afc27b579e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='buildingDropDown']</value>
      <webElementGuid>54ed24be-427d-42f8-9a4d-b9e41551b771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarsExampleXxl']/ul/li[2]/div/a</value>
      <webElementGuid>78d001fa-3c92-460e-a212-0a4be4fe650a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Buildings')]</value>
      <webElementGuid>49b9a745-3139-4b27-a713-9b80da89d866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>d61cb8c2-75f9-41e6-bbfe-dac5defc7f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building List'])[1]/preceding::a[1]</value>
      <webElementGuid>9db13dff-2e02-4623-977a-d08c9d8082a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building Report List'])[1]/preceding::a[2]</value>
      <webElementGuid>4c935960-7433-43c1-a667-d16d0a5556e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buildings']/parent::*</value>
      <webElementGuid>c2c223b9-75b1-4ed0-9122-83a071d0d128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a</value>
      <webElementGuid>8a39b478-40e3-489a-a231-2c1899344cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'buildingDropDown' and (text() = 'Buildings' or . = 'Buildings')]</value>
      <webElementGuid>919b8f28-3f14-498c-a595-1d61ee7b16f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
