<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Select images ( You can select up to 5 images )</name>
   <tag></tag>
   <elementGuidId>d5e630b2-9e17-4c25-a03c-a37b63061d36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#images</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='images']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8d21508b-3188-4626-ba04-733211a9848e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>images</value>
      <webElementGuid>85f2250b-cdbe-4139-b7cd-16f2dd8f20fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default mt-2 p-3 text-center text-muted rounded</value>
      <webElementGuid>c751a753-da09-4aaa-a4a5-fe011b7416f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select images ( You can select up to 5 images ) </value>
      <webElementGuid>b696fb41-88d8-433b-a26e-5e9280a84e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;images&quot;)</value>
      <webElementGuid>3fa26e5b-a289-42d5-9bc5-070f8846d07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>19f2cc7c-b341-4719-b026-57f13bc4e404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>images</value>
      <webElementGuid>24467bd9-8e9c-432c-b7da-c779d33a9731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default mt-2 p-3 text-center text-muted rounded</value>
      <webElementGuid>c64fbacc-ec05-4936-b898-e3d705894946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select images ( You can select up to 5 images ) </value>
      <webElementGuid>d1d0ad0f-3d61-4b67-8dde-06ca38b14fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;images&quot;)</value>
      <webElementGuid>c5f79b6b-b581-4a1e-af5f-b3cb36410f79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='images']</value>
      <webElementGuid>9af779bc-c826-4728-826c-170ed40bae1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Images'])[1]/following::label[1]</value>
      <webElementGuid>3ed05507-d14a-4683-a06c-68594022e8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter comment here...'])[1]/following::label[2]</value>
      <webElementGuid>67dbbca7-be42-42c3-8350-dabc9e293b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>3d485065-6872-43c7-a025-b0a46da4306a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'images' and (text() = 'Select images ( You can select up to 5 images ) ' or . = 'Select images ( You can select up to 5 images ) ')]</value>
      <webElementGuid>5e983755-91d8-423a-af59-ce9480ffac3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
