<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select images</name>
   <tag></tag>
   <elementGuidId>a5765aba-fda8-464b-a96a-c95e836f112f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#images > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='images']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>48767dca-0804-4864-9270-ecbf5a9724bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select images</value>
      <webElementGuid>e7d44198-b4b7-47b4-9e22-7b5fd5efcdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;images&quot;)/span[1]</value>
      <webElementGuid>348721cd-a466-4614-a4d7-49d5005aea1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef08240a-df60-42af-9576-b7c2422ff9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select images</value>
      <webElementGuid>a17bd894-2a90-426e-af3f-6f1a905c9564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;images&quot;)/span[1]</value>
      <webElementGuid>933ef98a-56af-4215-8f86-97cd79d6d7ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='images']/span</value>
      <webElementGuid>ace4e451-c442-4c86-8a22-d0d7ec2837e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Images'])[1]/following::span[1]</value>
      <webElementGuid>14469a98-33d6-4665-8ad9-7f5f5a86204c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter comment here...'])[1]/following::span[1]</value>
      <webElementGuid>49428e4b-0a09-44ce-bb7a-ea783191f3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='( You can select up to 5 images )'])[1]/preceding::span[1]</value>
      <webElementGuid>b0d54765-08ab-4361-800b-a3b1619a27f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::span[1]</value>
      <webElementGuid>b8352d76-18c0-44dd-9243-d95d9edf01f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select images']/parent::*</value>
      <webElementGuid>40a19860-9b05-464d-bb3a-9e4f94914fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span</value>
      <webElementGuid>82900b38-4bf0-47e3-9734-4dc842875b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select images' or . = 'Select images')]</value>
      <webElementGuid>fa43e0b4-004a-4aea-8d40-cbd23dd955c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
