<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ALLCVGCVVFFCAHNWHVP5HVPIIIHVPIVMKREM_28ff37</name>
   <tag></tag>
   <elementGuidId>12a9d8df-73b3-4d64-ad21-bf0068498d63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-select.mt-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Portfolio'])[2]/following::select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>afe3535a-a1e8-4869-a1f7-ec3e8133ad42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select mt-2</value>
      <webElementGuid>2910f532-ec8b-4695-af1b-c2655d6d2c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALLCVGCVVFFCAHNWHVP5HVPIIIHVPIVMKREMMACHIMMOCMMPCMMMPFMMPF2MMPF3MPIXPIX2SBAFSBAF2SPONSORTWORIV</value>
      <webElementGuid>aa98ce88-0a2f-46e8-9032-3a21179c94c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;container-fluid p-0 main-container&quot;]/div[@class=&quot;container pt-4&quot;]/div[@class=&quot;card container-middle&quot;]/div[@class=&quot;card-body&quot;]/app-portfolio-home[1]/app-portfolio-grid[1]/div[@class=&quot;row mt-2&quot;]/div[@class=&quot;col-md-4 col-lg-3 col-xl-2 mt-2&quot;]/select[@class=&quot;form-select mt-2&quot;]</value>
      <webElementGuid>1f853079-6f92-4e34-b4ba-f1f054a49e84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portfolio'])[2]/following::select[1]</value>
      <webElementGuid>a242f7c8-4359-452d-9a32-4366670200d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portfolio Rollup'])[1]/following::select[1]</value>
      <webElementGuid>19636168-d014-4919-9c89-e56c1a2bf5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portfolio'])[3]/preceding::select[1]</value>
      <webElementGuid>18db695f-e8fb-42fe-8505-8af13e7d807b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::select[1]</value>
      <webElementGuid>098b5f9f-8519-4d69-965f-34b018d78279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>79db8fa9-c1d5-42f0-b4df-5135316e187a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'ALLCVGCVVFFCAHNWHVP5HVPIIIHVPIVMKREMMACHIMMOCMMPCMMMPFMMPF2MMPF3MPIXPIX2SBAFSBAF2SPONSORTWORIV' or . = 'ALLCVGCVVFFCAHNWHVP5HVPIIIHVPIVMKREMMACHIMMOCMMPCMMMPFMMPF2MMPF3MPIXPIX2SBAFSBAF2SPONSORTWORIV')]</value>
      <webElementGuid>99d2cd70-51b5-4ebf-b828-b541c79f2ed1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
