<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectPerimeter Walls Exterior Wall Framing</name>
   <tag></tag>
   <elementGuidId>746c7d03-bef8-407f-be3b-485519236dcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-8.col-xs-12 > #inspectedBy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inspectedBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c6ae84f5-adb0-4279-8c96-622615680ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>SubCategoryID</value>
      <webElementGuid>33d97667-15bf-4e88-8580-e51a4704420d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inspectedBy</value>
      <webElementGuid>9ff00a69-6471-46aa-8234-8d92786cd52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inspectedBy</value>
      <webElementGuid>dea95dda-8e7f-47f8-97a1-bd20af56880a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Subcategory</value>
      <webElementGuid>fe000fb8-2028-48a1-8af5-ea6fd523f824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select col-md-2 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6df038b0-456c-48c2-9af7-e39ea3779902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectPerimeter Walls Exterior Wall Framing </value>
      <webElementGuid>8e684c36-ee59-42f5-817e-b19971ed7e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body capex-items&quot;]/app-capex-report-form[1]/div[@class=&quot;col-md-12&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;row mt-2 px-2&quot;]/div[@class=&quot;col-md-8 col-xs-12&quot;]/select[@id=&quot;inspectedBy&quot;]</value>
      <webElementGuid>2f1e0697-0ed0-4784-990f-ba098bc11956</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inspectedBy']</value>
      <webElementGuid>d4ef3126-cc4e-4970-9408-d5bbfb73560e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>53f5d870-0172-4a54-87db-3854a29e946c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>df759d7f-722c-4ceb-a702-be89fe44ab18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c3031a1c-abd8-4b39-82e8-35fd38840e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'inspectedBy' and @id = 'inspectedBy' and @placeholder = 'Subcategory' and (text() = 'SelectPerimeter Walls Exterior Wall Framing ' or . = 'SelectPerimeter Walls Exterior Wall Framing ')]</value>
      <webElementGuid>6658cd99-9325-4add-ad20-7365fb604f25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
