<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_test_btn btn-light btn-sm d-print-none</name>
   <tag></tag>
   <elementGuidId>b6fa4017-f484-420a-8f3e-af9bb40e3d21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-light.btn-sm.d-print-none</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='download-container']/div/div[2]/div/app-variance-analysis/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13b9d260-7b1c-4932-9b38-de1253852b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light btn-sm d-print-none</value>
      <webElementGuid>bbbb8e78-c56d-4ab6-81df-2d4f7de56767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;download-container&quot;)/div[@class=&quot;print-container&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;mt-5&quot;]/app-variance-analysis[1]/div[1]/div[@class=&quot;mt-3&quot;]/div[@class=&quot;d-flex justify-content-between align-items-start mb-4&quot;]/button[@class=&quot;btn btn-light btn-sm d-print-none&quot;]</value>
      <webElementGuid>d45e8c4e-967b-452b-bb69-176cfcd884c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div[2]/div/app-variance-analysis/div/div[2]/div/button</value>
      <webElementGuid>99ffa3b8-385c-4003-86ab-278bf12a51cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/following::button[1]</value>
      <webElementGuid>b726f7df-448f-4f7d-903d-c1240569c18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Variance Analysis'])[1]/following::button[1]</value>
      <webElementGuid>1db312c3-639c-482c-ad56-64b34d9bd919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Image'])[1]/preceding::button[1]</value>
      <webElementGuid>f96c72fe-b428-4f91-8cc3-c68ddca7e129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenant Delinquencies'])[1]/preceding::button[1]</value>
      <webElementGuid>47546fe9-ea9c-4bb9-bc1b-399cfc462779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/button</value>
      <webElementGuid>7c5ee95e-b070-412d-ab46-387648abe4a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
