<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Comic Sans MS_angular-editor-textarea</name>
   <tag></tag>
   <elementGuidId>784c6197-747e-4d84-8f47-88d28c652ad3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.angular-editor-textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='download-container']/div/div[2]/div/app-variance-analysis/div/div[2]/div/angular-editor/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a510e6fe-b70b-418a-bdb1-a2067b9c3f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>angular-editor-textarea</value>
      <webElementGuid>b76aca67-0d40-4037-8dba-4548ca23c180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0d6d6ac-c9c7-4fc8-921f-de6fb2e548bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d0b23cd4-31e9-453b-b9c5-b03f001cc749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc8fa18a-237c-43a4-a0c6-8ab2410ebf40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;download-container&quot;)/div[@class=&quot;print-container&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;mt-5&quot;]/app-variance-analysis[1]/div[1]/div[@class=&quot;mt-3&quot;]/div[@class=&quot;mb-4&quot;]/angular-editor[@class=&quot;ng-untouched ng-valid ng-dirty&quot;]/div[@class=&quot;angular-editor&quot;]/div[@class=&quot;angular-editor-wrapper show-placeholder&quot;]/div[@class=&quot;angular-editor-textarea&quot;]</value>
      <webElementGuid>99f192c6-b302-41cf-9c16-2c6487da55f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div[2]/div/app-variance-analysis/div/div[2]/div/angular-editor/div/div/div</value>
      <webElementGuid>d76cf1d3-c2b3-49df-8a3d-bf56f4ca00f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//angular-editor/div/div/div</value>
      <webElementGuid>cbc8d038-357b-4670-8504-086dfa5a9c41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
