<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YesNo</name>
   <tag></tag>
   <elementGuidId>e79976cf-c2b2-408c-b2c2-47ef45c97f0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-select.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='download-container']/div/div[6]/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>97fb1b8e-8303-4557-aa45-8ea7dd34de0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4ced8f0b-2da3-407d-badf-d5629494bb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YesNo` </value>
      <webElementGuid>c1da9502-ecc2-4e5a-868a-b9ae97c8cabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;download-container&quot;)/div[@class=&quot;print-container&quot;]/div[@class=&quot;row mt-4 px-2&quot;]/div[@class=&quot;col-md-3 col-xs-6 d-flex align-items-center&quot;]/select[@class=&quot;form-select ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>ab46fe68-2cb6-44bb-8314-ab0a6dd64260</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div[6]/div[2]/select</value>
      <webElementGuid>dfb28dd5-5f1d-41a7-9d55-efe378d0bc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenant Financials Requestable'])[1]/following::select[1]</value>
      <webElementGuid>d34aeb62-f923-40be-8ff5-7e2a87447c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MMPF2'])[1]/following::select[1]</value>
      <webElementGuid>34d0f66c-3ca8-4372-857c-ebf7d237d29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Received'])[1]/preceding::select[1]</value>
      <webElementGuid>c835321d-ce9e-4fb1-b6e3-552ce6ccf44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Receivable'])[1]/preceding::select[1]</value>
      <webElementGuid>23042d94-bba6-48e8-b483-169acb498792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='`']/parent::*</value>
      <webElementGuid>62e6623c-162b-43be-9a19-76430e7fa8c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>619beac9-1296-4606-8b4f-38b0549eb52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'YesNo` ' or . = 'YesNo` ')]</value>
      <webElementGuid>3c6d343c-4c03-49f0-8e90-acdadd2e3405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
