<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Units_units</name>
   <tag></tag>
   <elementGuidId>1d230329-31b7-4eef-90aa-f7da5f820dd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#units</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='units']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ec73a8e-8f0e-4f49-a672-16bf682f0008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>units</value>
      <webElementGuid>7fd180db-f70c-4c2b-86c0-9fd076558021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f2125f8-89d7-4b1d-9c18-1ad1fbf8b59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>units</value>
      <webElementGuid>6b268339-0bd2-4f8f-8353-a50fe5a87a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>units</value>
      <webElementGuid>c001ae8f-149c-4fa3-8ca9-9758d796c42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Units</value>
      <webElementGuid>26a00d97-9774-4624-beb4-b1201fb9aff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>2e29db1f-0e05-4d82-a789-0ce72b8b2fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;units&quot;)</value>
      <webElementGuid>802d929f-b648-4bf8-b326-6a5af2c3a5ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='units']</value>
      <webElementGuid>5e32592c-0358-49e5-84a3-da76ab642300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/input</value>
      <webElementGuid>05a93787-01f1-4ad6-9d0a-f9c7a243a54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'units' and @id = 'units' and @placeholder = 'Units']</value>
      <webElementGuid>4b92e663-1d78-4970-a30c-6f2078ba25a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
