<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in_loginfmt</name>
   <tag></tag>
   <elementGuidId>92b74e4b-db32-42d6-8719-86537c28cf22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i0116</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i0116']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>785c1416-7925-408a-b4d3-42dfa36377bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>c50929bf-c393-4a56-b4df-b9eb503fe690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginfmt</value>
      <webElementGuid>0ac82eb2-ad33-4e3f-b440-85bfb2e3dccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i0116</value>
      <webElementGuid>b24844a9-8532-4913-8328-2d2bd2355845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>113</value>
      <webElementGuid>c86be1e1-4d0c-4d7c-8d5e-f89b4c0b7215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ltr_override input ext-input text-box ext-text-box</value>
      <webElementGuid>f3617de9-e4ac-45fc-a75a-2ab884ff1181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8be5fac3-f2be-4107-a3f1-950c8ca63375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-report-event</name>
      <type>Main</type>
      <value>Signin_Email_Phone_Skype</value>
      <webElementGuid>e468ab60-5d1c-4e4d-a03d-10dbaeb592ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-report-trigger</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>5bd6947e-f2f4-490c-a805-e8b9242b840c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-report-value</name>
      <type>Main</type>
      <value>Email_Phone_Skype_Entry</value>
      <webElementGuid>517d2f71-a177-416d-830a-f61d8f42d2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>
                    attr: { lang: svr.fApplyAsciiRegexOnInput ? null : 'en' },
                    externalCss: {
                        'input': true,
                        'text-box': true,
                        'has-error': usernameTextbox.error },
                    ariaLabel: tenantBranding.unsafe_userIdLabel || str['CT_PWD_STR_Username_AriaLabel'],
                    ariaDescribedBy: 'loginHeader' + (pageDescription &amp;&amp; !svr.fHideLoginDesc ? ' loginDescription usernameError' : ' usernameError'),
                    textInput: usernameTextbox.value,
                    hasFocusEx: usernameTextbox.focused,
                    placeholder: $placeholderText</value>
      <webElementGuid>deec2e12-6660-4cb8-b0bd-8d00d14cd700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter your email, phone, or Skype.</value>
      <webElementGuid>9e97959d-a68b-4c1d-8cad-74dcad7a5248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>loginHeader usernameError</value>
      <webElementGuid>c3a8aec5-06a0-493c-89f2-002eb57dfa86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email, phone, or Skype</value>
      <webElementGuid>28a5abc2-bac4-4001-9ca2-a838a4975d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i0116&quot;)</value>
      <webElementGuid>e5803f0f-d8b8-4c4d-b675-e0e453caeae0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i0116']</value>
      <webElementGuid>8f5cbaa3-6cce-40dc-a961-59efb2109dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lightbox']/div[3]/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>61eab760-f4fc-4a14-96b5-c1e1c7fcac1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>81ad3f90-ede2-40ed-8f0e-6695ed511f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'loginfmt' and @id = 'i0116' and @placeholder = 'Email, phone, or Skype']</value>
      <webElementGuid>977ca965-46a4-4d8c-ae32-9b1a871619e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
