<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Immediate Cost ()_immediateCost</name>
   <tag></tag>
   <elementGuidId>2b6bb744-ab4f-48fc-bee6-df98857305d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#immediateCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='immediateCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4033a7a-e3a5-4e7e-a087-679c53199469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>immediateCost</value>
      <webElementGuid>1f1a02d2-a96f-4ad8-937c-4ab565f3cd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2d3db55d-f228-4aff-81a2-ce47b9ce5079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>immediateCost</value>
      <webElementGuid>ef860778-949c-4eaa-a2a8-30cee30193cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>immediateCost</value>
      <webElementGuid>cea9363d-f76f-4f9a-be96-ad6c1cad7464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Immediate Cost ($)</value>
      <webElementGuid>c1b6c59e-1f02-4b34-8f78-26affb0c7b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-2 ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>28c7ee2f-fc70-4122-a0b5-e37d7844da8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;immediateCost&quot;)</value>
      <webElementGuid>6f24d425-2bf8-4a6a-b1b5-8b53a00bcb88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='immediateCost']</value>
      <webElementGuid>f49a3eae-08fe-4dfc-a881-993d50814d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/input</value>
      <webElementGuid>bf0d234a-394a-4a36-b8d2-6e95e336e0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'immediateCost' and @id = 'immediateCost' and @placeholder = 'Immediate Cost ($)']</value>
      <webElementGuid>37683d8b-510d-4cb5-bff1-752bfae132e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
