<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YesNo_1</name>
   <tag></tag>
   <elementGuidId>f8bd56b1-4784-4935-85ff-6dd7f652ece6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fundsInEscrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fundsInEscrow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>88c4d59d-8294-48f6-822f-26ee8c9ce8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>fundsInEscrow</value>
      <webElementGuid>b0ac2ec3-04f5-4ea0-88a5-6101c13091e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fundsInEscrow</value>
      <webElementGuid>fb9fa281-c47e-4f96-bf10-3e66da2d082e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fundsInEscrow</value>
      <webElementGuid>46218d16-c253-4146-8f2c-89f22a79a58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Funds In Escrow</value>
      <webElementGuid>cb1b814e-3113-4d08-8d98-86b522437713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select col-md-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3ed8c2db-5c17-44d2-bc3f-fce0a02df22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YesNo</value>
      <webElementGuid>30066944-a842-4bce-a17d-004f694cbf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fundsInEscrow&quot;)</value>
      <webElementGuid>baed76d0-bd3b-463d-a61c-2a3ed237b4bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fundsInEscrow']</value>
      <webElementGuid>2d1fecb3-afbe-4d19-aa5b-bbf324aecb86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funds In Escrow'])[1]/following::select[1]</value>
      <webElementGuid>f3dc61ce-b177-4c0b-996a-f98b3b9ba51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recoverable'])[1]/following::select[2]</value>
      <webElementGuid>5f613b52-ee66-4c35-9a8a-8d50ecfd7fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expense Type'])[1]/preceding::select[1]</value>
      <webElementGuid>45a18157-cf33-429a-baed-37bb836ce443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Immediate Cost ($)'])[1]/preceding::select[2]</value>
      <webElementGuid>20669ec6-30c1-4eaa-9ca7-54255d86eb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/select</value>
      <webElementGuid>ae13e01d-0aa9-4001-8440-32952b01314e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fundsInEscrow' and @id = 'fundsInEscrow' and @placeholder = 'Funds In Escrow' and (text() = 'YesNo' or . = 'YesNo')]</value>
      <webElementGuid>62260779-0a67-4158-8840-88c7c00d2fa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
