<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectLandlordTenantDualOther</name>
   <tag></tag>
   <elementGuidId>cb107d9e-e964-46ea-9056-2d4ea5394b63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#responsibility</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='responsibility']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d54ec06a-ac5d-4ef4-b667-f70946b5a22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>responsibility</value>
      <webElementGuid>d3db6a66-e160-4cdd-a7a8-c4892834d02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>responsibility</value>
      <webElementGuid>333d464b-dfa0-4622-96ac-6d5e197d5a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>responsibility</value>
      <webElementGuid>5b88a57b-eea2-41ef-93bf-a52f85b19fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Responsibility</value>
      <webElementGuid>f1f1d3cf-2da7-49b0-87ea-4ae6fdc49a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select col-md-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>832b67dc-26f0-4349-9f69-02eeb34b05c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectLandlordTenantDualOther</value>
      <webElementGuid>9e9a6e9b-56d8-4f55-8ed4-e569734f0f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responsibility&quot;)</value>
      <webElementGuid>01125e7f-636f-40c0-b358-8361e7f9417f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='responsibility']</value>
      <webElementGuid>78cac6f2-e9f0-4455-acde-7fd3e814ba7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsibility'])[1]/following::select[1]</value>
      <webElementGuid>db71b97f-f4a9-4494-adbb-0329e1d78d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance/Repair Details'])[1]/following::select[1]</value>
      <webElementGuid>1d81e8d2-58c8-4487-8cd8-dd15534cd278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recoverable'])[1]/preceding::select[1]</value>
      <webElementGuid>df0d01b7-ef13-449f-a8dc-7e6f1ad23adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funds In Escrow'])[1]/preceding::select[2]</value>
      <webElementGuid>de61e884-4bb4-43f7-8006-943d0004fdb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/select</value>
      <webElementGuid>83ad4f14-7e61-46b8-94ca-7940e05ac9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'responsibility' and @id = 'responsibility' and @placeholder = 'Responsibility' and (text() = 'SelectLandlordTenantDualOther' or . = 'SelectLandlordTenantDualOther')]</value>
      <webElementGuid>8521dc14-8a90-4df1-8218-09b4c46023f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
