<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectADA Compliance Building Envelo_ab7b5e</name>
   <tag></tag>
   <elementGuidId>469bb29a-c42b-467a-8c58-26e4387bd8f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#categoryId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='categoryId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>31ee281b-2d5a-48ac-832c-f74c6fad5039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>categoryId</value>
      <webElementGuid>2b4234e5-0f1c-4da3-9522-5e0789b52256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>categoryId</value>
      <webElementGuid>3079853e-edb4-458f-ab9d-66530c262b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categoryId</value>
      <webElementGuid>a98ecdca-1673-426d-a38f-27280178c914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Category</value>
      <webElementGuid>14227f2b-bb48-430d-9671-92ab77f33abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select col-md-2 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>43e752d0-3ad6-4e64-918d-824d5fdcd0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectADA Compliance Building Envelope Electrical Elevator Interior Life Safety &amp; Generator Mechanical Systems Other Plumbing Roofing Site Elements Structural </value>
      <webElementGuid>a9e042fb-6bf3-45be-9f08-73f67485ceef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoryId&quot;)</value>
      <webElementGuid>afbd2463-7792-46bd-8962-bd12e58a606f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='categoryId']</value>
      <webElementGuid>d1cd0180-09f0-4d59-a57b-05e180689c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>2f030e73-bf19-407f-bf4f-57aa2034eafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>249b9638-8117-4a98-9463-c61f1a68160f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c3372bb0-3d61-488c-8902-c92c7f0677f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'categoryId' and @id = 'categoryId' and @placeholder = 'Category' and (text() = 'SelectADA Compliance Building Envelope Electrical Elevator Interior Life Safety &amp; Generator Mechanical Systems Other Plumbing Roofing Site Elements Structural ' or . = 'SelectADA Compliance Building Envelope Electrical Elevator Interior Life Safety &amp; Generator Mechanical Systems Other Plumbing Roofing Site Elements Structural ')]</value>
      <webElementGuid>6dcf6752-75ae-486e-baa6-5a6a163791a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
