<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectRMCapital</name>
   <tag></tag>
   <elementGuidId>fe1d7797-6733-4628-a77e-189eb201164f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expenseType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='expenseType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8fb4b9f9-6097-4468-b5d0-2cbb6e74945d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>expenseType</value>
      <webElementGuid>cad2e20c-1d15-436e-afb1-cc13ba1a19e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expenseType</value>
      <webElementGuid>3d3abdf3-d485-48b4-9ceb-eabdd12ef8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expenseType</value>
      <webElementGuid>649d636f-2006-4745-82ae-26b817043b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Expense Type</value>
      <webElementGuid>b44bb32b-04d9-4757-8519-7e959fa2d3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select col-md-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a56927a5-efaa-4837-8e77-59da76aa21a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectR&amp;MCapital</value>
      <webElementGuid>5bf5434b-e37d-4860-9173-468fbe825297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expenseType&quot;)</value>
      <webElementGuid>ecc8602c-3b5d-4fd2-9e54-0f2e93b84950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='expenseType']</value>
      <webElementGuid>fcf2afa3-a4d3-46a4-9b6d-b97de81261e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expense Type'])[1]/following::select[1]</value>
      <webElementGuid>53b175a4-5f0f-4a8d-a761-af819d8cc252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funds In Escrow'])[1]/following::select[2]</value>
      <webElementGuid>318ad34e-4291-4625-ac07-79c4136d7858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Immediate Cost ($)'])[1]/preceding::select[1]</value>
      <webElementGuid>56863e27-f5dc-40d7-81b8-96fcfc30d687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Units'])[2]/preceding::select[1]</value>
      <webElementGuid>f2c27fae-5b9e-4a24-9099-1c8d86d6830d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/select</value>
      <webElementGuid>b9ff5f29-c179-4962-bc38-827fa3ae31df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'expenseType' and @id = 'expenseType' and @placeholder = 'Expense Type' and (text() = 'SelectR&amp;MCapital' or . = 'SelectR&amp;MCapital')]</value>
      <webElementGuid>a582e2f0-e1c4-4b2a-adda-ab4e5006ecfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
