<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectBrickEIFSHardiboardMultiple (D_ddb88f</name>
   <tag></tag>
   <elementGuidId>0e7b64f2-a53c-4046-bc24-36e4984192f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#componentId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='componentId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f3db111a-f5a3-4add-ac09-4e36517d564d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>componentId</value>
      <webElementGuid>3cb9ff64-f5a7-4aef-b749-932aed807895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>componentId</value>
      <webElementGuid>3abff2ac-06f1-4f69-8370-e31b8a12814b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>componentId</value>
      <webElementGuid>b046a5e6-f6c2-4534-9f66-6002a15b77b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Component Name</value>
      <webElementGuid>bcad44a2-cbfa-4b07-bd97-13c9b223437e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select col-md-2 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>1a74ccd3-5c5a-445e-bf04-aa737b731f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectBrickEIFSHardiboardMultiple (Describe)OtherPre-Cast ConcretePre-Finished Metal PanelStoneStucco/PlasterTilt WallVinylWood</value>
      <webElementGuid>ec0b2c00-156d-4137-bedc-4a1a8849557c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;componentId&quot;)</value>
      <webElementGuid>fca637fc-c599-4c9a-bb45-862b203c902b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='componentId']</value>
      <webElementGuid>01c47788-abf0-4add-b991-0e82ad4c6041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>dbe6697a-fa43-4c44-a3ae-101494abdc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance/Repair Details'])[1]/preceding::select[1]</value>
      <webElementGuid>6fca1358-eed6-4c0f-a79b-9c387652cde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsibility'])[1]/preceding::select[1]</value>
      <webElementGuid>6ea2fc29-3982-42f4-91bf-41c2e0a03133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>a6c30c6b-7af9-4385-8487-f8ed75f37cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'componentId' and @id = 'componentId' and @placeholder = 'Component Name' and (text() = 'SelectBrickEIFSHardiboardMultiple (Describe)OtherPre-Cast ConcretePre-Finished Metal PanelStoneStucco/PlasterTilt WallVinylWood' or . = 'SelectBrickEIFSHardiboardMultiple (Describe)OtherPre-Cast ConcretePre-Finished Metal PanelStoneStucco/PlasterTilt WallVinylWood')]</value>
      <webElementGuid>df107488-2d23-4d73-bccd-5f92f4230bac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
