<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ScheduledIn progressCompleted</name>
   <tag></tag>
   <elementGuidId>e215ce8f-5580-44c6-a31c-de633b46cbf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#statusId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='statusId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bfb2ad11-27ee-4ba4-a0f9-4c07d429c43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>statusId</value>
      <webElementGuid>21edfb0d-98bf-4228-a624-32a8616b73a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>statusId</value>
      <webElementGuid>52944069-72ee-40dd-999e-f510f95d74e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>statusId</value>
      <webElementGuid>3692fbda-a8d9-447e-8d9d-bf929e272b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>eaa2e21c-a216-42ab-88fe-833084e7f205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select col-md-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d4146ed3-1f62-4c3b-b891-1078825d4ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ScheduledIn progressCompleted</value>
      <webElementGuid>97726455-6d71-460c-a95a-655f58c8bda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;statusId&quot;)</value>
      <webElementGuid>893e27c0-7f96-4835-9c0b-2a1f78912876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='statusId']</value>
      <webElementGuid>d18ec89d-554c-4a28-aa41-02b5f3a59c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::select[1]</value>
      <webElementGuid>97454e2b-b07a-4479-8bd5-0e5d57af4231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scheduled Maintenance Date'])[1]/following::select[1]</value>
      <webElementGuid>86c105ff-a8c8-496c-a255-0eeec5fb06ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>3397f89d-8d66-4b8d-8ed1-106e47756227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::select[1]</value>
      <webElementGuid>3b9590da-cd2a-4fa3-a0da-9518841e7614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/select</value>
      <webElementGuid>18d5c574-351a-4496-aee9-0b6e6a521a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'statusId' and @id = 'statusId' and @placeholder = 'Status' and (text() = 'ScheduledIn progressCompleted' or . = 'ScheduledIn progressCompleted')]</value>
      <webElementGuid>7d4a6b5a-f01b-408d-aa94-eac7bcc629ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
