<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectPerimeter Walls Exterior Wall Framing</name>
   <tag></tag>
   <elementGuidId>6a8e22bf-3225-424e-8c66-3fd4819c38b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subCategoryId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='subCategoryId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>72dc1f17-651b-48a3-bf85-c5edf66390a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>subCategoryId</value>
      <webElementGuid>d7eed7f3-54f6-46b7-8aa1-f34e17bdf0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subCategoryId</value>
      <webElementGuid>1dcd8ced-f092-4ca7-bf42-bb31d6247fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subCategoryId</value>
      <webElementGuid>b8dbe3dd-7417-4531-8ee4-9332e8226da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Subcategory</value>
      <webElementGuid>407c82ac-2bea-4e89-ad26-b74945850e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select col-md-2 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c00e2287-5efd-416f-b38b-e7584948713c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectPerimeter Walls Exterior Wall Framing </value>
      <webElementGuid>baeebb87-0bba-4df8-b891-045ebfc993c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subCategoryId&quot;)</value>
      <webElementGuid>5c02e020-d22b-4046-8cc4-9d258842a1c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='subCategoryId']</value>
      <webElementGuid>96ae75e3-121e-4345-a81e-98e5426f0a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>6ece7b9b-5f0f-4da5-b4df-eb5749f64a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>c712a237-eec0-4c20-acc3-2cb4d79bb72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/select</value>
      <webElementGuid>70cda774-fc79-427d-99e0-47e0785c3c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'subCategoryId' and @id = 'subCategoryId' and @placeholder = 'Subcategory' and (text() = 'SelectPerimeter Walls Exterior Wall Framing ' or . = 'SelectPerimeter Walls Exterior Wall Framing ')]</value>
      <webElementGuid>ee006a32-ff81-4a99-ad5c-a9d14079f826</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
