<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_MaintenanceRepair Details_maintena_840f81</name>
   <tag></tag>
   <elementGuidId>69c3dbef-bd8c-4185-a085-80e5552cf59b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maintenanceDetails</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='maintenanceDetails']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0a4674f3-a4c2-4045-807b-52f8acd8e03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>maintenanceDetails</value>
      <webElementGuid>961e635d-14ea-474a-8878-ac6d356f5f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>967aaa9a-e05f-4973-b236-a6e55950b056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maintenanceDetails</value>
      <webElementGuid>7c6c4e99-0b3e-46af-99f9-292611467137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maintenanceDetails</value>
      <webElementGuid>76325a94-f31a-4e8b-a759-a16fa7d2910c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Maintenance/Repair Details</value>
      <webElementGuid>6aac1eb0-137d-4a08-9689-8fcb60fbd432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-2 ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>a821a380-4215-48de-bfcf-8ca6708f4fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maintenanceDetails&quot;)</value>
      <webElementGuid>649c89ef-4543-44c1-bfbc-70d3fc202742</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='maintenanceDetails']</value>
      <webElementGuid>18d79134-1567-4bbf-92fd-cc3a82f3412e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/textarea</value>
      <webElementGuid>4efa199e-167d-4b60-8d8a-3e5d13cdf58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @name = 'maintenanceDetails' and @id = 'maintenanceDetails' and @placeholder = 'Maintenance/Repair Details']</value>
      <webElementGuid>b200fdad-2870-43c7-9e3c-0972554ee252</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
