<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Property Type_propertyType</name>
   <tag></tag>
   <elementGuidId>9573bf14-fee5-4cd8-8880-3ef7255b75da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#propertyType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propertyType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7172edd7-9fa1-4603-bcd3-8be0af15ab08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>df16787c-a07a-4d40-9191-6701f1db862b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyType</value>
      <webElementGuid>43c80eb6-2297-4213-bf86-37a99af4eebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Property Type</value>
      <webElementGuid>c78199df-194c-4a8d-aae9-8d3897b36def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>1f92bed3-632a-41dd-b851-3a29b7598ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>c9f514ca-ccf8-4ff8-9fba-04c0d0ba15c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyType&quot;)</value>
      <webElementGuid>cdd4c4f4-d4a9-4903-8d97-d504489471c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propertyType']</value>
      <webElementGuid>43d31a09-c726-491a-9c18-c723acace04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>51bc5ecb-bae4-4f90-93ab-51549c2f35a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'propertyType' and @placeholder = 'Property Type']</value>
      <webElementGuid>33b4b716-0986-4608-9340-52e9504a7cbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
