<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Portfolio</name>
   <tag></tag>
   <elementGuidId>ec3a2c84-fa78-4f60-ba51-940f7816eb6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#portfoliosDropDown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='portfoliosDropDown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>02f4c56c-665b-4de8-8cf4-1300f79bef6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>portfoliosDropDown</value>
      <webElementGuid>9e98d30c-a30f-4a59-83be-29dfcf41c253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>5b60f5e4-b2ef-416f-9763-1d85bab40ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c808db6d-faab-474f-8c55-9658cd499cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>eb383492-7fc9-4cba-8473-b16ecd1df9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link d-flex align-items-center show</value>
      <webElementGuid>a91307ba-8c01-4f71-a511-85c45fe6c20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Portfolio</value>
      <webElementGuid>e6086193-485a-4582-836c-fcf526618b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portfoliosDropDown&quot;)</value>
      <webElementGuid>fe3433a0-7390-4551-8055-6522f017a03f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='portfoliosDropDown']</value>
      <webElementGuid>a128e735-7e7a-442b-84da-1003af91a476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarsExampleXxl']/ul/li[3]/div/a</value>
      <webElementGuid>433a8377-41ad-4652-a4b3-110fe2f2e9e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Portfolio')]</value>
      <webElementGuid>21e29fa0-e3ad-462a-bd09-312082446aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Building Report'])[1]/following::a[1]</value>
      <webElementGuid>430cded7-8fad-41f1-8eb0-2b7df23c7c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building Report List'])[1]/following::a[2]</value>
      <webElementGuid>8f4441a7-7353-4a39-bf10-f17edf1ce668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portfolio List'])[1]/preceding::a[1]</value>
      <webElementGuid>2eead5f0-dae8-4763-b026-38d43160fe91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Portfolio'])[1]/preceding::a[2]</value>
      <webElementGuid>f9e2b609-2636-40ff-b28a-fd56d50ead95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Portfolio']/parent::*</value>
      <webElementGuid>1e7482a9-be7e-4bb2-bdf5-08098eea427c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/a</value>
      <webElementGuid>4934d314-7f31-469e-846f-0dbca34147d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'portfoliosDropDown' and (text() = 'Portfolio' or . = 'Portfolio')]</value>
      <webElementGuid>f1c3ef13-02b8-4cd5-9e86-88e4a64e30c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
