<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Comment</name>
   <tag></tag>
   <elementGuidId>56ae9357-0c25-4b81-b4cc-cd9135ac49c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.angular-editor-textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='download-container']/div/app-portfolio-overview/div[2]/div/div/div/angular-editor/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d40d8cd-9e2c-40ea-b2b1-518e49089325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>angular-editor-textarea</value>
      <webElementGuid>73d50c08-71e3-4629-85fc-e239f47fc51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e1c493bf-1d27-4f36-a866-768c4bdb2c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>28e92eee-4ab8-4348-a98c-c7acafec6ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9f625d65-4e49-4929-93b1-57cdaf41d7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comment</value>
      <webElementGuid>e1139b3c-2a86-4d3c-9fb2-3b1e7a538965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;download-container&quot;)/div[@class=&quot;print-container&quot;]/app-portfolio-overview[1]/div[@class=&quot;row mt-2&quot;]/div[@class=&quot;col-xs-12 col-md-6 col-lg-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 mt-2&quot;]/angular-editor[@class=&quot;ng-untouched ng-valid ng-dirty&quot;]/div[@class=&quot;angular-editor&quot;]/div[@class=&quot;angular-editor-wrapper&quot;]/div[@class=&quot;angular-editor-textarea&quot;]</value>
      <webElementGuid>b7021bc8-62a9-452d-a096-22bc43e804af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/app-portfolio-overview/div[2]/div/div/div/angular-editor/div/div/div</value>
      <webElementGuid>01457d27-44a7-4482-984e-eca07c6995a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comic Sans MS'])[1]/following::div[7]</value>
      <webElementGuid>e9dbbabb-05bb-45f2-b0ca-b73a9cfd0d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calibri'])[1]/following::div[7]</value>
      <webElementGuid>7ff4c711-7372-4dec-b6a0-861db1ed704f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter text here...'])[1]/preceding::div[1]</value>
      <webElementGuid>9c5703df-a17e-4869-bb95-9621dc1a2218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::div[2]</value>
      <webElementGuid>bba59b80-5c0f-4def-b25c-e7c8e04d58e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Comment']/parent::*</value>
      <webElementGuid>23a97507-02e2-48a4-b097-566227972862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//angular-editor/div/div/div</value>
      <webElementGuid>0b6b425b-4ef8-4b98-8ed7-c8356eb649d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Comment' or . = 'Comment')]</value>
      <webElementGuid>90e4351a-1ed2-4f95-aed3-31d8acc1b3a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
