<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MonthQuarter</name>
   <tag></tag>
   <elementGuidId>5b9f5277-2068-4f69-a6d1-e68f290b7c24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filterMethod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filterMethod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>321f4053-e3a7-43e4-a506-1f96c83fb0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterMethod</value>
      <webElementGuid>cc7a8670-e45b-4cac-92b8-bd25627bbb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterMethod</value>
      <webElementGuid>69b283f5-c47b-41ca-8c99-f495451153a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>filterMethod</value>
      <webElementGuid>5a87db36-6c52-4891-9455-9b9cd886b405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Period type</value>
      <webElementGuid>540401a6-c08c-4d42-a803-260758e7d02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c83e304c-791f-482c-9274-658e22d2a1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MonthQuarter</value>
      <webElementGuid>351e8be2-3aa3-4c6e-9e36-ff36f4a6f51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterMethod&quot;)</value>
      <webElementGuid>a07d9b6b-ed77-48a8-b1c8-e92e7a812314</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filterMethod']</value>
      <webElementGuid>cf14211d-e9ca-4ff0-a576-4a8e6dcdc1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div[2]/div/form/div/div/select</value>
      <webElementGuid>11da20f9-7ab9-4bd0-8686-9924db1dd3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Period type'])[1]/following::select[1]</value>
      <webElementGuid>90fde657-5a86-44e1-b5c4-a9fe8cc9adba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rollup Portfolio'])[1]/following::select[1]</value>
      <webElementGuid>d7faad76-5fcf-4b40-9f41-7fda997d0ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Financial Year or Month'])[1]/preceding::select[1]</value>
      <webElementGuid>86a24d66-5e3c-486d-a491-21a33d59107a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan'])[1]/preceding::select[1]</value>
      <webElementGuid>8e0eb898-171a-4dea-a31e-1017ff983c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e5b05623-77d0-4ca7-ab90-45f2d11ba23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filterMethod' and @name = 'filterMethod' and (text() = 'MonthQuarter' or . = 'MonthQuarter')]</value>
      <webElementGuid>024e43cf-9a8d-44e7-8bcc-74f06ad91504</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
