<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Edit</name>
   <tag></tag>
   <elementGuidId>29f92c62-c6bb-42ba-8105-88be4f62ff2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ms-4.me-4 > a.icon-link > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='download-container']/div/div[2]/div[2]/div[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>68a1c443-e236-4169-a212-3a913165a1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>d78aebc8-6cb1-4508-bc52-beadf323aaa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;download-container&quot;)/div[@class=&quot;print-container&quot;]/div[@class=&quot;row mt-4 d-print-none&quot;]/div[@class=&quot;col-12 col-sm-6 col-md-5 d-flex justify-content-end align-items-center mt-4 mt-sm-0&quot;]/div[@class=&quot;ms-4 me-4&quot;]/a[@class=&quot;icon-link&quot;]/span[1]</value>
      <webElementGuid>5c2aa0fb-4d5f-4e1a-9f6e-f69ea5ff0f1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div[2]/div[2]/div[3]/a/span</value>
      <webElementGuid>a1c6cee7-4276-4658-976f-104d6c78c166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::span[1]</value>
      <webElementGuid>2ecc1c2a-f60c-4c06-bb2e-5374e41d8210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/following::span[2]</value>
      <webElementGuid>c3d23621-3cf0-4609-b970-3ceb67353705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details Table'])[1]/preceding::span[1]</value>
      <webElementGuid>8ad87a79-40cb-4c86-ad07-4fb8112bafa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly Financial Performance (000s) - July'])[1]/preceding::span[2]</value>
      <webElementGuid>5ea8a177-dd44-4fb7-987b-c5837bdb426d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>58e9945e-d4fe-427f-86ad-e89f2ee8c3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/span</value>
      <webElementGuid>fca5e723-78a6-4f73-94a3-326138243de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>afbf0d12-b028-4219-987f-002ba90c3e2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
