<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Capital Expenditure</name>
   <tag></tag>
   <elementGuidId>4493b87a-bbfa-413b-8a0d-4297069627fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#capexDropDown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='capexDropDown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>adec1962-a710-496e-91b7-3492287dfd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>capexDropDown</value>
      <webElementGuid>f8a77b30-c65b-4122-ae20-6cba50f6ea62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>3c740138-a411-400c-ac27-41cf53f6cee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4641504f-25a3-4c4b-8def-9216224802a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>e0efbd0d-33ab-4407-a26e-7847aa90d459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link d-flex align-items-center show</value>
      <webElementGuid>d9b52d6d-9248-4971-95d9-3473965be0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Capital Expenditure</value>
      <webElementGuid>a50fd41d-6d87-4b97-830f-0ca8b03bb548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;capexDropDown&quot;)</value>
      <webElementGuid>30ce3cc1-b8aa-4698-a05d-afe973896f46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='capexDropDown']</value>
      <webElementGuid>d5b69517-0f3e-497a-95b6-6587cdc746e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarsExampleXxl']/ul/li[4]/div/a</value>
      <webElementGuid>9473dbb6-98f4-4b88-b481-e3df295260b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Capital Expenditure')]</value>
      <webElementGuid>6282e437-e335-4ad6-9fbe-f99347637152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What-if? Portfolio'])[1]/following::a[1]</value>
      <webElementGuid>bfbc77ec-ddf1-46da-8680-533c19fc8833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Portfolio'])[1]/following::a[2]</value>
      <webElementGuid>a1b37e6f-6f04-42e8-9e67-e5b59b47b4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inspection List'])[1]/preceding::a[1]</value>
      <webElementGuid>d0b73334-0a34-494e-b063-ade49cbf465f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Inspection'])[1]/preceding::a[2]</value>
      <webElementGuid>0f621309-2669-4fbd-b466-88eb627b126b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Capital Expenditure']/parent::*</value>
      <webElementGuid>99d106f9-e334-45b4-b4f4-24e24c0c0aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/a</value>
      <webElementGuid>7f361606-8fb0-402a-9f1b-b22d9a5f8e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'capexDropDown' and (text() = 'Capital Expenditure' or . = 'Capital Expenditure')]</value>
      <webElementGuid>f9e7f048-b9cb-424e-8e6f-35fe5952c261</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
