<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Building name_buildingName</name>
   <tag></tag>
   <elementGuidId>552cac3d-db03-4be8-8864-46c187b652da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buildingName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buildingName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cc989a6-6d8f-420e-aa25-72278196a12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>a80d8c29-1315-4199-94f0-9e05c406a577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildingName</value>
      <webElementGuid>1987e394-14d3-48c2-abd6-df7647ca6c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Building name</value>
      <webElementGuid>94fc0262-c3ee-4bb1-aff6-fb55fe131ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>9bd55382-09d0-4f15-a628-cd22b3f0edfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>a702b78f-7f25-4932-93e1-51dd45e73036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buildingName&quot;)</value>
      <webElementGuid>308436fc-5e62-4a05-837a-c9e764e2f160</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buildingName']</value>
      <webElementGuid>ab883251-2f56-4978-aa6b-fe77cf8a7db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>2ec6eef0-5b65-4bc1-85c3-322e8d37b035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'buildingName' and @placeholder = 'Building name']</value>
      <webElementGuid>52fcbcd0-9dd3-42a6-a777-22b4291f453b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
