<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit Cost ()_unitCost</name>
   <tag></tag>
   <elementGuidId>b694991e-3c3c-49e9-afe9-2d45cc3bfddf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unitCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unitCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fefb522-c9a2-437c-b4ac-55119b3c49f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>unitCost</value>
      <webElementGuid>7d61c355-a94e-4296-b90d-b052dde48e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a4aa6362-65be-4489-98cc-d386df75260f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unitCost</value>
      <webElementGuid>c3c0129f-f679-4f97-b46f-b5f04283351b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitCost</value>
      <webElementGuid>5ac25162-e133-463f-9db8-1d8958e2f7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Unit Cost ($)</value>
      <webElementGuid>c85e8ea1-b26f-4520-a87d-da50354c0658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-2 ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>32dcce91-2415-4416-bad2-82bf5ac419b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unitCost&quot;)</value>
      <webElementGuid>3d454ee1-6177-4bd9-935e-210fe4322943</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unitCost']</value>
      <webElementGuid>5066a776-10bb-414a-a78f-f4bfbca83927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/input</value>
      <webElementGuid>96eed527-c30d-43b3-acdc-005a1cb13a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'unitCost' and @id = 'unitCost' and @placeholder = 'Unit Cost ($)']</value>
      <webElementGuid>a93a7995-7c2e-4bf2-bc19-1fc70adee066</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
