<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Units_units</name>
   <tag></tag>
   <elementGuidId>f281e02d-a199-43ef-bf8b-979c37ae225d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#units</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='units']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>793ba61b-2bd3-4226-81dd-ce60e8d7c83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>units</value>
      <webElementGuid>e4c81d22-f038-4766-b05d-df6736dd64a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>524e8848-50e3-4089-9bb8-0bc49f2e9548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>units</value>
      <webElementGuid>2234e639-ffb6-4863-8bbc-72eee1b7151a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>units</value>
      <webElementGuid>e18cdae0-0dce-4048-a156-e6798a8520b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Units</value>
      <webElementGuid>d028a869-72d6-4370-84b8-fef63b6dde6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>be5732c0-3424-4f4d-b849-88e2f12b9b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;units&quot;)</value>
      <webElementGuid>e7097ac3-669e-422d-a182-eeaa1548e7b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='units']</value>
      <webElementGuid>d0ac3651-15be-44ef-95d2-fc2511db4d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/input</value>
      <webElementGuid>5681e467-d973-4497-ad48-dfb195507d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'units' and @id = 'units' and @placeholder = 'Units']</value>
      <webElementGuid>b79c2d9a-61f3-44a6-808d-8c9f61a0ba27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
