<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Immediate Cost ()_immediateCost</name>
   <tag></tag>
   <elementGuidId>55aa1d2d-e872-4701-84d5-f5331c7a6faf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#immediateCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='immediateCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c075d18f-5035-4b0b-9505-d4c9c9ea1064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>immediateCost</value>
      <webElementGuid>4b3077fb-0360-4cb9-9590-1e1f80d2e341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1eb513dc-7a14-4cd3-9561-107de6944604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>immediateCost</value>
      <webElementGuid>8e0d7f35-9736-4098-903e-913390db0a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>immediateCost</value>
      <webElementGuid>a1a2c43a-c644-4587-b616-50e65b411bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Immediate Cost ($)</value>
      <webElementGuid>2f4ba8e7-b6a7-4bdc-a73a-c92a60c6fb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-2 ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>f8129c80-d8e5-4be0-8e98-2bbc128d4164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;immediateCost&quot;)</value>
      <webElementGuid>372b8839-02fe-4dc1-8bc1-1a026c2aeb20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='immediateCost']</value>
      <webElementGuid>7905bb5e-b1d9-45ef-99e5-06bf76125e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/input</value>
      <webElementGuid>18d3cea6-9eab-4a13-9275-7e695cbe237a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'immediateCost' and @id = 'immediateCost' and @placeholder = 'Immediate Cost ($)']</value>
      <webElementGuid>d11a6343-6311-463c-9708-3be3b4668639</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
