<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YesNo_1</name>
   <tag></tag>
   <elementGuidId>cdc339ce-0526-464e-8ef6-2a6839f28af2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fundsInEscrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fundsInEscrow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c47426c9-740c-4ed9-a1d5-f64389ea0fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>fundsInEscrow</value>
      <webElementGuid>03d6cf8c-3417-4d56-bfa7-42f31806ebfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fundsInEscrow</value>
      <webElementGuid>709d9c74-72cb-4d3b-98b1-0a45aeb0cde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fundsInEscrow</value>
      <webElementGuid>f2c6da82-0a2e-43ee-92ec-50aa0db21d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Funds In Escrow</value>
      <webElementGuid>93dd57b6-b407-4855-b216-e1c20c77eb68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select col-md-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>01525a4e-88dd-4f08-903e-a2c2248b458a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YesNo</value>
      <webElementGuid>4cadd5dd-fd75-4fed-ae87-1ea55cb7233a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fundsInEscrow&quot;)</value>
      <webElementGuid>469fead5-507a-45cf-be26-759d9bc41241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fundsInEscrow']</value>
      <webElementGuid>8849e11c-0ad9-4a19-acfb-d0254c2600ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funds In Escrow'])[2]/following::select[1]</value>
      <webElementGuid>505abb23-df45-4dff-85bc-42e19b46d8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recoverable'])[2]/following::select[2]</value>
      <webElementGuid>ba03e3ff-1b1c-4885-8f01-fe953ccb8fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expense Type'])[2]/preceding::select[1]</value>
      <webElementGuid>aedd861c-0da3-4460-85e7-0ab29200abfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Immediate Cost ($)'])[1]/preceding::select[2]</value>
      <webElementGuid>10ce05f2-7078-4f23-85b0-d4c42a8ae804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/select</value>
      <webElementGuid>8ed821b2-b306-4486-8a8a-5dae5913ef3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fundsInEscrow' and @id = 'fundsInEscrow' and @placeholder = 'Funds In Escrow' and (text() = 'YesNo' or . = 'YesNo')]</value>
      <webElementGuid>ff9ccb32-a404-44b5-9382-855df1008a88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
