<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectADA Compliance Building Envelo_ab7b5e</name>
   <tag></tag>
   <elementGuidId>54196e42-56b1-43b0-8f9f-0435b2efa12e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#categoryId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='categoryId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ad8d7387-2326-4d8d-b8f3-1355fa9066b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>categoryId</value>
      <webElementGuid>45b88a2d-87cc-4408-8521-e92c54afc8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>categoryId</value>
      <webElementGuid>98c4fe2b-d86a-486e-9679-163a74f5f46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categoryId</value>
      <webElementGuid>f292c3d0-6306-4995-931a-c3356d1edb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Category</value>
      <webElementGuid>c2721ad2-4474-44bc-89eb-6d78d86a1a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select col-md-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>15b3fea8-a713-4643-bd4b-357c7a5d1215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectADA Compliance Building Envelope Electrical Elevator Interior Life Safety &amp; Generator Mechanical Systems Other Plumbing Roofing Site Elements Structural </value>
      <webElementGuid>39287c17-7044-4784-b7e4-3d68473d3fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoryId&quot;)</value>
      <webElementGuid>c45163c4-497a-4f8a-9d99-101933152682</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='categoryId']</value>
      <webElementGuid>6dd3c2d3-9645-4d70-8ed1-268228b78679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>8395d8c4-a3e5-4400-9dbf-38f0a9322be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>1944ba1a-c4ff-4fae-8bc2-888461365e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>afed548b-4185-4f4e-87b0-39d411a1fd29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'categoryId' and @id = 'categoryId' and @placeholder = 'Category' and (text() = 'SelectADA Compliance Building Envelope Electrical Elevator Interior Life Safety &amp; Generator Mechanical Systems Other Plumbing Roofing Site Elements Structural ' or . = 'SelectADA Compliance Building Envelope Electrical Elevator Interior Life Safety &amp; Generator Mechanical Systems Other Plumbing Roofing Site Elements Structural ')]</value>
      <webElementGuid>d229dca0-d329-4e12-bdc3-e82bb4ee8d98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
