<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectLandlordTenantDualOther</name>
   <tag></tag>
   <elementGuidId>12b8a0ad-ded9-41ef-93d6-5440514b6a3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#responsibility</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='responsibility']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4b624c33-0055-418c-a5b0-e9e160191ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>responsibility</value>
      <webElementGuid>7602b573-1583-4315-91e3-a8c7f5b2ac07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>responsibility</value>
      <webElementGuid>d91e64a9-81f7-4156-a1b9-ca9d3e819830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>responsibility</value>
      <webElementGuid>a71541cd-7411-4f13-a671-1779bc85c770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Responsibility</value>
      <webElementGuid>597ba899-e6e3-4f30-9350-870a7c0411b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select col-md-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>fe91d2d2-c3ef-43a9-b9a5-28fa2182da4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectLandlordTenantDualOther</value>
      <webElementGuid>9be8faa1-dd4a-41f6-8623-8ae954c1c011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responsibility&quot;)</value>
      <webElementGuid>ab97a6b6-64f6-48bf-9c8a-fd77a536ac25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='responsibility']</value>
      <webElementGuid>4d05c009-6ad7-424c-aa93-f3d674164668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsibility'])[2]/following::select[1]</value>
      <webElementGuid>75aec72f-7edb-4369-b10b-6a233e1b1733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance/Repair Details'])[1]/following::select[1]</value>
      <webElementGuid>723822be-38c1-47d1-86f4-469d59f1949c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recoverable'])[2]/preceding::select[1]</value>
      <webElementGuid>f23c6cc8-1681-4f9b-bda9-e1f70972eedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funds In Escrow'])[2]/preceding::select[2]</value>
      <webElementGuid>499ca32d-c4b8-4fcf-b861-2bfabee3ff20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/select</value>
      <webElementGuid>fed42793-cf7e-425c-b34b-b6b22f96b670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'responsibility' and @id = 'responsibility' and @placeholder = 'Responsibility' and (text() = 'SelectLandlordTenantDualOther' or . = 'SelectLandlordTenantDualOther')]</value>
      <webElementGuid>3bce6faa-6821-4c15-b46a-33deb1078d60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
