<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectBreaker PanelExterior Pad-Moun_18f956</name>
   <tag></tag>
   <elementGuidId>a5c471bf-8fee-4043-b3e4-c1eb4643c352</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#componentId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='componentId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5e52f7f1-8bc7-4ea0-929f-0de6a93352a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>componentId</value>
      <webElementGuid>738b315a-0676-4f00-b9ee-ed7ba34966d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>componentId</value>
      <webElementGuid>eb722e6f-4b99-4467-8400-07e95eedc78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>componentId</value>
      <webElementGuid>97c6c466-5be8-4659-87f4-99a632f67395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Component Name</value>
      <webElementGuid>d4799627-dfa0-416e-95f9-626091f14738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select col-md-2 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>f16fd10b-b47d-4da5-acaf-016b47188452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectBreaker PanelExterior Pad-Mounted TransformerInterior TransformerLightning ProtectionMain SwitchgearOtherSurge Protection (Device)Surge Protection (Whole Building)</value>
      <webElementGuid>94ec6e23-f6c7-4cfb-b778-88ebd1d5b1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;componentId&quot;)</value>
      <webElementGuid>d89d0e4d-24fb-43ed-83a2-dfb066c86f93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='componentId']</value>
      <webElementGuid>505d3f8b-5e38-44fa-ace5-904813cc8d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>203ca01a-1c9a-4839-9c69-88a23908556b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance/Repair Details'])[1]/preceding::select[1]</value>
      <webElementGuid>d8a01880-7f7b-465c-9a24-e5ec633e3e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsibility'])[2]/preceding::select[1]</value>
      <webElementGuid>d3a6f6b3-b4b6-45f6-a1f5-478824db7eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>f86c6494-def2-470d-b242-4d0ad4cd974e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'componentId' and @id = 'componentId' and @placeholder = 'Component Name' and (text() = 'SelectBreaker PanelExterior Pad-Mounted TransformerInterior TransformerLightning ProtectionMain SwitchgearOtherSurge Protection (Device)Surge Protection (Whole Building)' or . = 'SelectBreaker PanelExterior Pad-Mounted TransformerInterior TransformerLightning ProtectionMain SwitchgearOtherSurge Protection (Device)Surge Protection (Whole Building)')]</value>
      <webElementGuid>554a1e8f-1cd4-4d5d-bd11-071778bac3ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
