<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectRMCapital</name>
   <tag></tag>
   <elementGuidId>3dca343e-ec57-4f82-af2f-1172d66a93fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expenseType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='expenseType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ff72cbb8-acb7-4cf6-aabd-d2a0b93d8d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>expenseType</value>
      <webElementGuid>f2f131c7-c254-432b-ac16-6b1fcf7f48bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expenseType</value>
      <webElementGuid>54133a39-6c44-4ff6-b033-c48d9ec2bdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expenseType</value>
      <webElementGuid>97c398bd-53df-46cc-86c5-0f8820e3b112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Expense Type</value>
      <webElementGuid>8884d502-bbf2-461c-85ad-5732d0c33e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select col-md-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>cb43e68f-3195-46c6-981a-3786ae1441ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectR&amp;MCapital</value>
      <webElementGuid>4fe8d287-dc26-4f9f-be92-c33efb347f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expenseType&quot;)</value>
      <webElementGuid>42f1502e-9cf5-4bf1-af9c-1e1654d1d45e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='expenseType']</value>
      <webElementGuid>2762c2b9-f3d4-4dbb-bca1-606a9cf586e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expense Type'])[2]/following::select[1]</value>
      <webElementGuid>e0bffa75-1718-4608-b8cf-d43669e0bb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funds In Escrow'])[2]/following::select[2]</value>
      <webElementGuid>cc7e3415-2442-4b31-b15a-4ea05137cc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Immediate Cost ($)'])[1]/preceding::select[1]</value>
      <webElementGuid>5c93c140-2f88-48e8-b0ed-80c5e44f70d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Units'])[2]/preceding::select[1]</value>
      <webElementGuid>33fbc056-d344-4701-a6c3-e5f5fa766499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/select</value>
      <webElementGuid>eb586fa3-96ef-4c0d-bf8c-d7c25e5dd267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'expenseType' and @id = 'expenseType' and @placeholder = 'Expense Type' and (text() = 'SelectR&amp;MCapital' or . = 'SelectR&amp;MCapital')]</value>
      <webElementGuid>b902a42b-5097-4434-8fff-5d7ecdf06a41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
