<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Building Grade_grade</name>
   <tag></tag>
   <elementGuidId>cf140cbd-d6bc-41f9-aeac-427b32454ae2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grade</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='grade']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06275bad-a722-4ff6-aca1-fdea7543e182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>9c087501-f032-49d6-9b20-1ed40532fbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grade</value>
      <webElementGuid>b7a5f4ec-3273-4ab3-8a41-b27090ae9c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Building Grade</value>
      <webElementGuid>d03e04a4-71c7-4f6d-a745-b2813b2f671b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>7138a5dc-2787-403f-8b40-c852a9ef7c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>7f7ae476-a70e-44cf-969e-011d9b04bf03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grade&quot;)</value>
      <webElementGuid>2964db03-7b4c-40b5-8fa1-4b30b8b4c344</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='grade']</value>
      <webElementGuid>67cfd8b0-e22f-4209-b3d6-2f7c4b7842bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>ce7c0452-0b24-4bd0-ac02-170930e08380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'grade' and @placeholder = 'Building Grade']</value>
      <webElementGuid>b27eba4c-8286-4356-925e-bfe78eebb23d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
