<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_YES</name>
   <tag></tag>
   <elementGuidId>0ca92a58-8786-4822-b920-e477820dbccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.btn-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='cdk-drop-list-1']/tr[5]/td[6]/div/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6ffb79e8-1685-4c29-be5f-5c6021f22582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-danger</value>
      <webElementGuid>8834c0cf-bfa1-400a-b578-c745f2705eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YES</value>
      <webElementGuid>c27a952a-3887-467e-ba36-f23f65bebce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-drop-list-1&quot;)/tr[@class=&quot;cdk-drag strip&quot;]/td[@class=&quot;text-center d-print-none&quot;]/div[@class=&quot;c-dialog&quot;]/div[@class=&quot;c-dialog-bubble py-2 px-4 single&quot;]/div[@class=&quot;pt-1 text-end&quot;]/button[@class=&quot;btn btn-sm btn-danger&quot;]</value>
      <webElementGuid>c37df908-4400-4b1e-b235-2b1a12912e83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='cdk-drop-list-1']/tr[5]/td[6]/div/div/div[2]/button</value>
      <webElementGuid>6e531b11-dc47-469b-b77f-d5a23acfc4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to delete?'])[1]/following::button[1]</value>
      <webElementGuid>86e7d9c9-521b-4047-90a2-7260d863b72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a@gmail.com'])[1]/following::button[2]</value>
      <webElementGuid>e0c9aafe-458c-4df7-8d30-ef90aef8c55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/preceding::button[1]</value>
      <webElementGuid>d1cfb438-fdf4-497d-a508-d843c0d83764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leases'])[1]/preceding::button[2]</value>
      <webElementGuid>7ded3985-71ad-470c-958d-7cd92f7c1c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='YES']/parent::*</value>
      <webElementGuid>008b99cf-c260-4eb0-8938-af5f0beaf673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/div[2]/button</value>
      <webElementGuid>6a7ba5ed-9ea3-4152-b0f8-d30127824521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'YES' or . = 'YES')]</value>
      <webElementGuid>9857af4f-8a68-4b6f-967b-68abd78d542c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
