<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_ffgmail.com_svg-inline--fa fa-trash-alt_1387ac</name>
   <tag></tag>
   <elementGuidId>22a61910-e920-44fe-8dd9-1f52989023e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='ff@gmail.com'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>fda809b2-8423-497e-aecf-4e086243b44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>06e4cced-f218-4d9f-a541-72f9f46bf21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>089542d1-bd01-41b1-8c2e-a4c9c5316bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f54af5bc-0633-4e22-ba1e-dcb4b9704772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prefix</name>
      <type>Main</type>
      <value>fas</value>
      <webElementGuid>da812096-8884-4788-a757-7d0988d807fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>trash-alt</value>
      <webElementGuid>04f6c11d-1032-493d-be2d-e0584ce34659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-trash-alt fa-w-14</value>
      <webElementGuid>d892fc54-ff34-498f-b4a1-c21964880553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>d12335d7-3613-49f8-aff8-893bbd707c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 448 512</value>
      <webElementGuid>c6d11cf0-1a08-416b-87cb-b5e4f1d6b7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-drop-list-1&quot;)/tr[@class=&quot;cdk-drag ng-star-inserted&quot;]/td[@class=&quot;text-center d-print-none ng-star-inserted&quot;]/button[@class=&quot;button-border ms-1 cgrid-delete-row ng-star-inserted&quot;]/fa-icon[@class=&quot;ng-fa-icon grid-color&quot;]/svg[@class=&quot;svg-inline--fa fa-trash-alt fa-w-14&quot;]</value>
      <webElementGuid>dbb4a148-36d4-41e3-a6cf-d82ad3226ba8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ff@gmail.com'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>f99aaf37-5607-4d7b-88d3-60fd231b69c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='f'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>86c2ac94-3e14-4689-89f2-c3921f5cccf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leases'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>500e8d4d-a020-4e23-aca0-afbbc7e4d442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WALT'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>5ee2d8c5-2e5a-44b6-be8c-c7f87015ffe1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
