<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_09012022</name>
   <tag></tag>
   <elementGuidId>80703620-8663-47fc-8e12-8c925c340549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.text-end > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='cdk-drop-list-0']/tr/td[7]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8911f8d8-73bc-4f79-8e4c-39e29849d305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 09/01/2022 </value>
      <webElementGuid>3da35fd4-5494-4c30-9d7c-d7bf57b845fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-drop-list-0&quot;)/tr[@class=&quot;cdk-drag strip cdk-drag-disabled&quot;]/td[@class=&quot;text-end&quot;]/span[1]</value>
      <webElementGuid>009b2b91-3a0f-4568-8128-84247283ba9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='cdk-drop-list-0']/tr/td[7]/span</value>
      <webElementGuid>ed4269ab-8cc9-4f1e-9415-80eb6e6a93e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NH'])[1]/following::span[1]</value>
      <webElementGuid>e8028211-0f8b-451d-ba6d-f8921a763bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NeuroSpine'])[1]/following::span[2]</value>
      <webElementGuid>f79d0f0b-fc9f-489f-a43e-415258b2c9c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='----'])[1]/preceding::span[1]</value>
      <webElementGuid>326e0c30-2803-4592-9fb5-19f41d5e4bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='----'])[2]/preceding::span[2]</value>
      <webElementGuid>ad281201-a93a-4164-8928-4cf2fb6f8334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='09/01/2022']/parent::*</value>
      <webElementGuid>eb9613fe-78b0-4b28-9941-3d67987f4160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/span</value>
      <webElementGuid>ef5f1c35-1e7e-4862-b362-05a18a43637b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' 09/01/2022 ' or . = ' 09/01/2022 ')]</value>
      <webElementGuid>f4a237ee-d19d-4325-97f6-ffa997a2f087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
