<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Client Name_clientName</name>
   <tag></tag>
   <elementGuidId>105d30f8-f1fa-4e37-93c0-779ab311879c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clientName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clientName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba79d199-f655-4809-bc02-cb97de31f54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>956da30a-de4a-48f6-b328-c271e713d15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clientName</value>
      <webElementGuid>9820a91f-6d4d-4459-9fe4-244341485e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Client Name</value>
      <webElementGuid>820683cd-3e25-4448-a4b6-065cc0b69cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>f731ee72-2eec-4ea7-a4c3-301fd312e66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 ng-valid ng-touched ng-dirty</value>
      <webElementGuid>5103aabe-69af-4a20-8dc5-2b6ecd618fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientName&quot;)</value>
      <webElementGuid>753a72c7-6ca7-41e3-bc9d-742797396927</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clientName']</value>
      <webElementGuid>d7a02ef6-a9e4-44e6-8e17-02c5455dfa9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>35989d4c-d126-49c6-b09a-ee53677afec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'clientName' and @placeholder = 'Client Name']</value>
      <webElementGuid>7089383e-1586-4f3a-acdf-4a72c1ad08e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
