<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Portfolio</name>
   <tag></tag>
   <elementGuidId>c8244bd7-a198-40d3-bf04-4e2b3c2f14f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#portfoliosDropDown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='portfoliosDropDown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>31b7c2b3-8e11-4235-bd71-47b5f3e2f7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>portfoliosDropDown</value>
      <webElementGuid>a2dd78c2-cc3b-45fe-901d-20e9ee3c4266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>0d5533e3-e02f-4b1d-ad1f-c4e95938bcb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>20ed0510-5bc8-4c4b-976a-b06ced1f086e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>f6828e0f-9248-411c-9a71-ad5ceebbd691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link d-flex align-items-center show</value>
      <webElementGuid>b05087c3-2cf6-4558-9a39-50714799d9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Portfolio</value>
      <webElementGuid>b3dc5248-72fa-4d16-bbd8-365d90a901b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portfoliosDropDown&quot;)</value>
      <webElementGuid>1baca0e9-e6d2-4bb4-a663-22d11b58ac41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='portfoliosDropDown']</value>
      <webElementGuid>61d7bd27-e3ee-4950-a3ab-73589b613b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarsExampleXxl']/ul/li[3]/div/a</value>
      <webElementGuid>bf6fe2b5-65eb-4d46-b1c6-7d70613614f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Portfolio')]</value>
      <webElementGuid>5adc667d-8a11-4e29-a937-14c510d96ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Building Report'])[1]/following::a[1]</value>
      <webElementGuid>29406cf1-6c3e-4fcf-9d1a-575508adf624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building Report List'])[1]/following::a[2]</value>
      <webElementGuid>caa3da29-20b2-4524-bb11-1f9e5a4891a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portfolio List'])[1]/preceding::a[1]</value>
      <webElementGuid>9a7426ea-fa22-4cc2-93db-6d6148c7aedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Portfolio'])[1]/preceding::a[2]</value>
      <webElementGuid>a941d1d2-2b58-47c5-9e5e-ed1d1698789a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Portfolio']/parent::*</value>
      <webElementGuid>4dd1a2bd-7083-421d-8044-114aae255097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/a</value>
      <webElementGuid>9f3fd6f5-6909-4775-831b-02d12d8af48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'portfoliosDropDown' and (text() = 'Portfolio' or . = 'Portfolio')]</value>
      <webElementGuid>217e2672-2fe6-4b22-aaf8-8dea851d66b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
