<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_contactName</name>
   <tag></tag>
   <elementGuidId>b8f9cb9c-c21b-4121-9949-cc5e26c3c757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contactName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contactName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c91ffa9d-909e-44bb-9037-1f084f1e47a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contactName</value>
      <webElementGuid>1096e3fc-bf33-4baa-8d1a-9521b821da1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contactName</value>
      <webElementGuid>19104384-ac84-4191-91c0-4b27b581c483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contactName</value>
      <webElementGuid>878d2ab4-9ca2-478b-ab5c-fab3deb263b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Name</value>
      <webElementGuid>8568c310-bf00-42d0-97a6-d4633878b276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-2 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>32f4226d-dbd1-4ab1-a982-82a268f4aec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contactName&quot;)</value>
      <webElementGuid>a0b88c87-1a37-416e-a51a-772633ef4e32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contactName']</value>
      <webElementGuid>f94847a5-b833-4ee2-b12e-687a4bd3e4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>74e77010-dc94-450b-8cdf-c144487fc3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'contactName' and @id = 'contactName' and @placeholder = 'Enter Name']</value>
      <webElementGuid>1eded380-98c3-4157-80f0-50cb09c40691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
