<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_contactTitle</name>
   <tag></tag>
   <elementGuidId>0ba494ce-c335-4db5-be9b-db215892e056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contactTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contactTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2857e977-ff83-4f12-9202-62593c1a217b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contactTitle</value>
      <webElementGuid>64d47ea4-5507-47cf-9f57-8806823f55fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contactTitle</value>
      <webElementGuid>9cf771c2-9d1c-41bf-8e75-21ccaa0518e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contactTitle</value>
      <webElementGuid>3ee99951-f760-4b90-a1c4-c9f1cf1e80e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Title</value>
      <webElementGuid>4f7bf471-28d9-49c0-8156-3f89a31dd4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-2 ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>f3d0b797-7683-422d-b83d-30718f675bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contactTitle&quot;)</value>
      <webElementGuid>bf127c61-ba9d-4497-b111-3723c5e70973</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contactTitle']</value>
      <webElementGuid>2e337403-d7ad-4cfe-994c-eb0e83912305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>a88e56b0-44c5-4512-8cba-17d53c9e87f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'contactTitle' and @id = 'contactTitle' and @placeholder = 'Enter Title']</value>
      <webElementGuid>55de6068-68ac-432e-b758-87c4c2823125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
