<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_contactEmail</name>
   <tag></tag>
   <elementGuidId>8089dc2b-9325-432c-a3c5-288413d94c0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contactEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contactEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e888d5b-f709-4596-852a-29793621edce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>c0eb8016-c7a2-4b18-b826-bf854b1102d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contactEmail</value>
      <webElementGuid>53b59d0a-ff9b-47f0-98d4-a3fd83b9fe13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contactEmail</value>
      <webElementGuid>3e7c061f-98e7-4e56-983b-f5d9497c6165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contactEmail</value>
      <webElementGuid>0b143840-f8a0-4e9d-94dd-0246514f3346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Email</value>
      <webElementGuid>9ae4f5cc-622f-44f0-b351-e2da0a366c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-2 ng-untouched ng-invalid ng-dirty</value>
      <webElementGuid>e909a344-aa56-4ed1-a246-d7853249cda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contactEmail&quot;)</value>
      <webElementGuid>2cb0420a-778c-4df2-ab44-3287dce7322a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contactEmail']</value>
      <webElementGuid>1afb7976-ecf4-421d-aca3-89dce709c3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>01ab5f5e-66c9-4dbb-b428-fec493853c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'contactEmail' and @id = 'contactEmail' and @placeholder = 'Enter Email']</value>
      <webElementGuid>2aca3ed5-9717-4588-bc09-d5fcab346339</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
