<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone number_contactPhone</name>
   <tag></tag>
   <elementGuidId>59fb847f-b8f3-459a-bf94-22db710a49c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contactPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contactPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c7947b0-7d38-4e0c-9437-8d7a156a0087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contactPhone</value>
      <webElementGuid>0ef4daa0-4618-45bc-b650-539c75b2cc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contactPhone</value>
      <webElementGuid>f26a2bb7-8e4d-4c4f-a802-2b2dad39447f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contactPhone</value>
      <webElementGuid>2795e390-ea2a-46e4-89ce-e5ef75244d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Phone Number</value>
      <webElementGuid>9333ce14-02a9-454c-9465-66209cb8936f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-2 ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>e06cd451-bd38-4efa-95d4-c3e05ff342a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contactPhone&quot;)</value>
      <webElementGuid>d0ac0263-b89d-45b6-8907-7c5cadc3f3a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contactPhone']</value>
      <webElementGuid>e7e030b4-4b5c-468a-8b8b-b6a575809587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>1d093547-e7f6-48f3-8dfc-d606e75d378e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'contactPhone' and @id = 'contactPhone' and @placeholder = 'Enter Phone Number']</value>
      <webElementGuid>79531e79-bfca-47d0-83e0-bb23fc2d2714</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
