<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Building ID_buildingID</name>
   <tag></tag>
   <elementGuidId>860487c6-f9aa-440f-a7cc-0df8e7e1f4c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buildingID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buildingID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d45728fe-5b4f-4b53-b601-d7556ee4764b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ac9dc278-1cc5-4e3e-8bce-0b99dbe8285b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildingID</value>
      <webElementGuid>e7e57051-e170-49ee-bd6a-4601aadccf80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Building ID</value>
      <webElementGuid>526c7383-db14-475d-8f04-30a40c41bc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>8925dff9-7a16-430c-a3a8-38aee91a0af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>fec45b1d-d59a-4369-b10f-cb895398afe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buildingID&quot;)</value>
      <webElementGuid>466bd223-ab01-4958-97b9-4966716e3039</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buildingID']</value>
      <webElementGuid>2eae20c9-de81-42de-9055-0079b9aa3dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d90d3a3e-dd6a-4828-8dd2-b6b49d759c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'buildingID' and @placeholder = 'Building ID']</value>
      <webElementGuid>5969d4f7-e27f-45f9-b3ce-878be0152a7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
