<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primary Inspected By_inspectedBy</name>
   <tag></tag>
   <elementGuidId>edaab2f9-8522-44e5-8922-fe475e8b9455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inspectedBy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inspectedBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f221537-a3ff-4bf9-b940-0cdf6bccd602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>inspectedBy</value>
      <webElementGuid>e19e60ae-88dc-4352-8b98-54a31bd70187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ff0cd49-07ec-4614-b6a5-ae857d228fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inspectedBy</value>
      <webElementGuid>926ec4b8-06a3-4d1a-903b-d0925ba1f76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inspectedBy</value>
      <webElementGuid>1da15d5f-e53c-4303-b24b-0eedfba2f703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Inspected By</value>
      <webElementGuid>b7921cf9-505d-43f2-9349-290ca1d74aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>7feda4a6-978f-4066-a29b-0f1d98d9fa94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inspectedBy&quot;)</value>
      <webElementGuid>f14aff5c-9ac6-4123-92c8-a8081a6bc5db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inspectedBy']</value>
      <webElementGuid>83cac206-e73d-4a63-a1bd-51c0060b8327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div/form/div/div[2]/input</value>
      <webElementGuid>f21ed8d4-ab80-4151-b33e-6ab6049eb58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>fa569677-eda3-44ea-b0a4-6655628c74e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'inspectedBy' and @id = 'inspectedBy' and @placeholder = 'Inspected By']</value>
      <webElementGuid>6024de81-f9a1-4024-8c34-f4e69d128db8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
