<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Building Grade_buildingCondition</name>
   <tag></tag>
   <elementGuidId>1c876b1c-03e3-4579-8e84-1418d5f5ca59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buildingCondition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buildingCondition']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9aa2c5a7-280c-40af-91c1-fae2e183ec61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>buildingCondition</value>
      <webElementGuid>73ea38a1-b48e-4bdb-903b-ba07dec87f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb3c9d05-34aa-4125-943c-8e0d38362a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buildingCondition</value>
      <webElementGuid>52b0e4ea-8e98-422d-8e7c-d59eebcc04da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildingCondition</value>
      <webElementGuid>4d97c5e3-ae2c-4774-a1c8-ccc6b5f2d121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Building Grade</value>
      <webElementGuid>51cb5434-6aab-42f1-b26f-6fa1d78f7cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f5c254b5-66d7-4570-b9d8-d6603df7e4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buildingCondition&quot;)</value>
      <webElementGuid>e76c1319-5c93-4af3-82a1-a55006496aa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buildingCondition']</value>
      <webElementGuid>a709706e-1a17-4bb0-a162-2b8234c69151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div/form/div/div[5]/input</value>
      <webElementGuid>2fa302e0-235e-40cb-9e76-e9035148ed80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>20a26c83-5d8b-4336-9fec-458396b746c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'buildingCondition' and @id = 'buildingCondition' and @placeholder = 'Building Grade']</value>
      <webElementGuid>292fd9ed-2daf-4875-99dd-11b8bf3dcacb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
