<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number of Tenants_numberOfTenants</name>
   <tag></tag>
   <elementGuidId>479280a9-b880-4d8d-a2ad-18d5aa802926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberOfTenants</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberOfTenants']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af8c3ba2-3cba-4119-9c59-9bd90b8300a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>numberOfTenants</value>
      <webElementGuid>bd1e5105-695c-4e25-a9c7-7d6c5d6fde21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4f6dec3-c687-45bd-9778-4434c5938e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberOfTenants</value>
      <webElementGuid>cb252ce6-e5d1-49a1-9c30-aa43c2756352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberOfTenants</value>
      <webElementGuid>a6e443d1-94ea-4dc0-bd19-e9be1e239f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Number of Tenants</value>
      <webElementGuid>51b7f329-afe8-4953-ae71-983f70e6f38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ad8a3147-98f5-4629-9cac-c1b20c616b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberOfTenants&quot;)</value>
      <webElementGuid>7993c118-ae0f-45c6-8446-9e8c8c5bb025</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberOfTenants']</value>
      <webElementGuid>7ed4b2ff-4dfa-4025-b383-32490a5142c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div/form/div/div[8]/input</value>
      <webElementGuid>f08a9c4e-275c-4aa3-bbca-d2727e18ac4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>6171ffee-dbd5-46fc-9eac-9e90291bbb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'numberOfTenants' and @id = 'numberOfTenants' and @placeholder = 'Number of Tenants']</value>
      <webElementGuid>3ad34908-9ac1-48cb-9960-b9b08c81024f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
