<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number of Stories_numberOfStories</name>
   <tag></tag>
   <elementGuidId>ebd6428f-11d7-4d00-b124-dfddbe84ffd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberOfStories</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberOfStories']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c320347-8e68-484d-9766-cee73d9675c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>numberOfStories</value>
      <webElementGuid>3c25583d-52c5-4d42-9095-0f9bac01a691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ce6c832-e2c4-4fd7-b650-ff9b7a4cdd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberOfStories</value>
      <webElementGuid>775de543-d924-4e22-884b-163351532528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberOfStories</value>
      <webElementGuid>5869a478-af48-4101-a7fd-21ecf0bfde12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Number of Stories</value>
      <webElementGuid>658a26a7-223f-4c43-b648-aa5b8521b31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b694ae2f-6ab8-41c3-b5cb-e0afbd95247c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberOfStories&quot;)</value>
      <webElementGuid>e693c480-1055-4a4b-9402-ab701e0b40d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberOfStories']</value>
      <webElementGuid>670e7dbe-9032-424e-b49b-e9008943c2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div/form/div/div[7]/input</value>
      <webElementGuid>bcec7c66-99f9-4995-b6ee-4dac5fe1c980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>0a694d19-060a-4808-a124-defa68ca453d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'numberOfStories' and @id = 'numberOfStories' and @placeholder = 'Number of Stories']</value>
      <webElementGuid>2bf20106-5152-4594-bb84-bfe9b674521e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
