<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Property Type_propertyType</name>
   <tag></tag>
   <elementGuidId>c7d2391f-de5b-4a7b-8aec-eeb44b84141a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#propertyType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propertyType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15cf9a11-820d-4dd3-b357-fb77c9f3df1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>propertyType</value>
      <webElementGuid>2cd36b25-85e3-4db6-9c6a-35a48280196f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5af32c1-ecf8-4fdf-8c54-3a84f082b47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propertyType</value>
      <webElementGuid>8d5da437-dd75-4896-a9b9-d67895523445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyType</value>
      <webElementGuid>d21dc719-bf04-42ea-93c1-852f30bd2d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Property Type</value>
      <webElementGuid>8d14a992-3e4d-4dc8-9057-3fffc99c2158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>116aa84c-1c1a-4cf7-abb5-6b8468775dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyType&quot;)</value>
      <webElementGuid>3d69110c-b45a-4dd1-ad92-c8dc3b13975f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propertyType']</value>
      <webElementGuid>cb4dc947-f18c-4af3-a952-04962e0082c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div/form/div/div[3]/input</value>
      <webElementGuid>85445cc2-b6e6-4277-8d0b-d61104cc9fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>f45aa7da-59b3-4e49-bc70-f8b3a584df48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'propertyType' and @id = 'propertyType' and @placeholder = 'Property Type']</value>
      <webElementGuid>1bca58c7-6de6-483f-8366-dabd04d047b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
