<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Site Description_siteDescription</name>
   <tag></tag>
   <elementGuidId>c820b42c-d130-4936-aa55-789727b0e3fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#siteDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='siteDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c7f7be0d-d29a-4867-a2c2-8989a652d667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>siteDescription</value>
      <webElementGuid>76ac48cf-8df4-4aa3-a0cc-29768d9992d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f496e5b-d1c9-4fcc-aa12-7184a3da64d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>siteDescription</value>
      <webElementGuid>0a061b7e-a92f-4cbe-92c7-a542dc3aea4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>siteDescription</value>
      <webElementGuid>65e54756-93bd-40b0-a4a7-cf8c86315c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Site Description</value>
      <webElementGuid>dd7d9c77-1603-440f-b4ee-5a44e5fafbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7e1fea95-f649-4faf-886d-bb1cfd1b3e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>68025818-39b1-4e85-ac11-ba7749f8b875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siteDescription&quot;)</value>
      <webElementGuid>598372e0-86ae-4db3-8f94-c539702c191c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='siteDescription']</value>
      <webElementGuid>27872448-bb6a-4654-9a01-f9eda0eca1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div/form/div[2]/div[2]/textarea</value>
      <webElementGuid>85566e95-ffca-4c75-b334-21be64a120ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>4d5d0325-7c27-4ace-8113-1fd19e77b5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @name = 'siteDescription' and @id = 'siteDescription' and @placeholder = 'Site Description']</value>
      <webElementGuid>30bc089e-d2bb-4b8d-9e35-6e92e9ab19ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
