<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buildings</name>
   <tag></tag>
   <elementGuidId>6ed365b4-aaec-465d-8268-c35fa61ce076</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buildingDropDown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='buildingDropDown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1dbf865d-6f5e-4b1c-8042-873f75e600e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildingDropDown</value>
      <webElementGuid>79fba8b1-67bd-49f0-854d-921ba05b3834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>7c56905b-54c6-4289-aa03-ec1e7f643b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c34a442a-0caa-44ff-abef-079b7c5537ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>ab701c02-20fc-47fc-95a8-3e78f848281a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link d-flex align-items-center show</value>
      <webElementGuid>013b4006-07fb-4e13-96a0-f3b27bfe4bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buildings</value>
      <webElementGuid>9be4f936-b171-4553-ac3b-254229817bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buildingDropDown&quot;)</value>
      <webElementGuid>448e2444-b1be-4e23-8759-e3e09a178d99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='buildingDropDown']</value>
      <webElementGuid>bc3a7f90-d095-43c6-b36a-d97409244283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarsExampleXxl']/ul/li[2]/div/a</value>
      <webElementGuid>258b7413-5c44-4ecf-b994-848148391c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Buildings')]</value>
      <webElementGuid>2f260be0-d953-464a-ac96-0e6f829d233e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>b0ed608e-e75d-4669-bbe4-6d23123b7254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building List'])[1]/preceding::a[1]</value>
      <webElementGuid>6e95272e-44bd-4525-ab58-0cac0b26c1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building Report List'])[1]/preceding::a[2]</value>
      <webElementGuid>0c28d98d-f968-4c68-983c-e7ca7d9944ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buildings']/parent::*</value>
      <webElementGuid>fcb2fc36-b855-48ad-9a8c-c49e3b282bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a</value>
      <webElementGuid>d4984f7d-4120-4744-b2ca-c76984d1fae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'buildingDropDown' and (text() = 'Buildings' or . = 'Buildings')]</value>
      <webElementGuid>7dca7871-e67a-4c56-936b-7b7b6e14f7cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
