<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_newone Portfolio</name>
   <tag></tag>
   <elementGuidId>c8a38c7c-a4ff-47bf-9e11-dc4bba79803c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.image-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='download-container']/div/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d78a5a02-fe1f-4b0a-9e9c-8b4a965dbbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-title</value>
      <webElementGuid>6468009f-7a6c-4046-8f39-c2a9547ab455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>newone Portfolio</value>
      <webElementGuid>9a0f4782-a524-4db4-b0e2-598d1f8c6359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;download-container&quot;)/div[@class=&quot;print-container&quot;]/div[@class=&quot;row portfolio-top&quot;]/div[@class=&quot;col-md-12 p-0&quot;]/div[@class=&quot;row image-content-bottom text-light&quot;]/div[@class=&quot;col-sm-12 ps-5&quot;]/div[@class=&quot;image-title&quot;]</value>
      <webElementGuid>51206505-563f-40bc-bf3f-2d73e85de73a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div/div/div[2]/div/div</value>
      <webElementGuid>1544115f-4170-49eb-b2f1-55b50ec23a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::div[3]</value>
      <webElementGuid>767273ed-6394-4f93-9273-fa82d3586754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[19]</value>
      <webElementGuid>b8cd2e6a-40ff-4047-bd83-df7b4685ab7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Period type'])[1]/preceding::div[1]</value>
      <webElementGuid>466693b7-cbed-452c-95ac-68b6192aa81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Financial Year or Month'])[1]/preceding::div[2]</value>
      <webElementGuid>808dc5b9-d8e8-4336-8e9f-5e608bcae5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='newone Portfolio']/parent::*</value>
      <webElementGuid>4d1b87f9-3201-4403-ba72-085523f4097f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div</value>
      <webElementGuid>0954d457-2c71-4578-a8c1-bf6cd207536e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'newone Portfolio' or . = 'newone Portfolio')]</value>
      <webElementGuid>89fc81f7-b44b-4605-b3a8-75e440df144f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
