<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Client Name_clientName</name>
   <tag></tag>
   <elementGuidId>7f186341-c0d3-4623-b030-0ab9f897c581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clientName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clientName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ef7852d-4997-4b41-a556-b6558471d92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>clientName</value>
      <webElementGuid>acb91d79-48e7-445b-b1fd-3497234e9204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ee69ba9-6510-4d03-97ac-bf52000a4f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>clientName</value>
      <webElementGuid>35842113-9969-4b6f-8b50-7ab4352821e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clientName</value>
      <webElementGuid>df7b4332-1204-4daa-8c53-7915a52d04dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Client Name</value>
      <webElementGuid>397e549c-5942-45c8-905d-a85306ee3259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 d-print-none ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>fdc6c468-c9d2-4cab-90e2-2f8a5882fe5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientName&quot;)</value>
      <webElementGuid>a1e92974-c3a4-4e75-ae2e-cf0500577e97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clientName']</value>
      <webElementGuid>74634ab6-1d12-47e5-b81f-218dd13f426c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div/app-building-report-overview/div[3]/form/div/div[4]/input</value>
      <webElementGuid>d0ae7819-91e0-499c-aa4b-fae84257985e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>9ed9ba71-e2ed-4d0b-87c5-4269aecceec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'clientName' and @id = 'clientName' and @placeholder = 'Client Name']</value>
      <webElementGuid>33a5123f-8e38-4bcb-b470-47406fbc65ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
