<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Leased Status_leasedStatus</name>
   <tag></tag>
   <elementGuidId>2f487839-16c8-41a4-8c66-864f00b34917</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leasedStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leasedStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cc920b2-a152-4f34-8683-bafa5e3bd36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>leasedStatus</value>
      <webElementGuid>b2101bb1-5a19-4012-af60-cd75e5fa505d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1cfe7546-d443-4af7-9b5e-7269bb12d6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leasedStatus</value>
      <webElementGuid>469147f7-0656-4cd9-99b2-6867b212aabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leasedStatus</value>
      <webElementGuid>0b73ef3a-5567-41ce-a77a-fda4ce8a0f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Leased Status</value>
      <webElementGuid>0381a9eb-cf5f-4f66-85b6-770588a9d9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return event.keyCode !== 69</value>
      <webElementGuid>34b2a325-f676-43ec-8744-e87ce2167284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 d-print-none ng-untouched ng-valid ng-star-inserted ng-dirty</value>
      <webElementGuid>e30b1de1-2158-4e30-a039-32009f9a1f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leasedStatus&quot;)</value>
      <webElementGuid>76da5c0c-8fa8-40f0-8b96-575f02e4f73f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leasedStatus']</value>
      <webElementGuid>0d06ced2-7e97-4725-a824-eaeebc17f784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div/app-building-report-overview/div[3]/form/div/div[8]/input</value>
      <webElementGuid>f209b432-b36a-477e-8af2-d24fa267a82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>700e583e-d854-489d-8ff4-bf0725ccedfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'leasedStatus' and @id = 'leasedStatus' and @placeholder = 'Leased Status']</value>
      <webElementGuid>97f3245f-afc5-45dc-b5d7-4bd9b3f64370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
