<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asset Manager_assetManager</name>
   <tag></tag>
   <elementGuidId>acd5e28a-fef2-4a5c-8ab0-e1ff19c8bcda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#assetManager</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='assetManager']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>707c94d4-cc96-4b65-b6cb-33d7851a79ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>assetManager</value>
      <webElementGuid>1308def5-e0eb-4e85-972a-3a49db939a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>959629f6-328e-4d40-94ec-1b560a3a9b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assetManager</value>
      <webElementGuid>a912ac71-85a8-4ec6-972d-98684b28bfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assetManager</value>
      <webElementGuid>ef3bd22a-90b8-4810-b6b1-b871938458ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Asset Manager</value>
      <webElementGuid>b7397dca-833f-4a1b-8301-4f339254801e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 d-print-none ng-untouched ng-valid ng-star-inserted ng-dirty</value>
      <webElementGuid>1a324a6e-9cbe-4e52-ba76-261cb50c3745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assetManager&quot;)</value>
      <webElementGuid>30786613-3596-4562-bee0-cc2a5e1be1d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='assetManager']</value>
      <webElementGuid>2a49f040-a8c0-4866-8928-a4ab269a3724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div/app-building-report-overview/div[3]/form/div/div[5]/input</value>
      <webElementGuid>858c4dd7-f575-4ced-9a5b-937eae56c0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>6487f3d3-0af0-4d1c-bcef-dde7cbd2068a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'assetManager' and @id = 'assetManager' and @placeholder = 'Asset Manager']</value>
      <webElementGuid>ee4e5810-881d-46b1-ba2f-4d5d9e4b63b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
