<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Property Type_propertyType</name>
   <tag></tag>
   <elementGuidId>f632c228-6ecd-4548-b096-25a04cd7ee87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#propertyType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propertyType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8adddc1-3e6c-4055-ae51-926fbf4c5dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>propertyType</value>
      <webElementGuid>2aa7e2cd-d4e2-47fc-b5ff-4c660b804849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd398e51-0fe6-43d1-bf25-ab373dfeb762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propertyType</value>
      <webElementGuid>cbf4fad7-3b3d-4ed2-85a6-bc9821c5184e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyType</value>
      <webElementGuid>9a6a0298-1c14-4243-a787-cbd12aac0cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Property Type</value>
      <webElementGuid>cbc380e9-28e9-4efa-a70d-f453b687b86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2 d-print-none ng-untouched ng-valid ng-star-inserted ng-dirty</value>
      <webElementGuid>e8d39ef3-9c46-4700-a5e9-918ba0bec951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyType&quot;)</value>
      <webElementGuid>c35c2d5c-c279-433a-8b2b-2805d1ba8f63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propertyType']</value>
      <webElementGuid>1e4a3cf9-1386-4c71-a76d-0131eed295db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='download-container']/div/div/app-building-report-overview/div[3]/form/div/div[6]/input</value>
      <webElementGuid>1faa51b1-1b45-4e47-a6be-8c4a8b315c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>cf5e2bc4-4186-4243-af24-40a3f269d36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'propertyType' and @id = 'propertyType' and @placeholder = 'Property Type']</value>
      <webElementGuid>afce657c-3c1a-46af-9145-58a4fc886b64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
